// src/renderers/solid-workbench/chat/ToolConnector.solid.tsx
import { createEffect, onCleanup, onMount } from 'solid-js'
import { resolveConnectorColor, type ToolConnectorStatus } from '../../../domains/tool/toolPresentation.ts'
import { toolConnectorMotionClass } from '../../../components/chat/toolIndicatorMotion.ts'
import type { ToolVisualState } from '../../../domains/tool/status.ts'
import type { WorkbenchAppearanceSnapshot } from '../../../domains/workbench/appearance.ts'
import type { ToolConnectorLayoutPort } from '../../../domains/workbench/toolConnectorLayoutPort.ts'
import { measureToolConnector } from './domToolConnectorMeasurement.ts'

export type ToolConnectorAppearance = Pick<WorkbenchAppearanceSnapshot,
  'toolConnectorMode' | 'toolConnectorColor' | 'toolConnectorStyle' | 'toolConnectorWidth' | 'toolConnectorOpacity'>

export interface SolidToolConnectorProps {
  connectorKey: string
  fromMessageId: string
  toMessageId: string
  status: ToolConnectorStatus
  visualState?: ToolVisualState
  appearance: ToolConnectorAppearance
  layoutPort: ToolConnectorLayoutPort
  colors?: { toolOk?: string; toolRun?: string; toolErr?: string }
}

export function SolidToolConnector(props: SolidToolConnectorProps) {
  let connector: HTMLDivElement | undefined
  let observer: ResizeObserver | undefined
  const state = () => props.visualState ?? 'unknown'
  const color = () => resolveConnectorColor(
    props.appearance.toolConnectorMode,
    props.status,
    props.colors ?? {},
    props.appearance.toolConnectorColor || 'rgba(0,0,0,0.12)',
  )
  const width = () => Math.max(1, Math.min(6, props.appearance.toolConnectorWidth || 2))
  const opacity = () => Math.max(0.1, Math.min(1, props.appearance.toolConnectorOpacity ?? 1))

  createEffect(() => {
    const measurementInputs = [
      props.appearance.toolConnectorMode,
      props.appearance.toolConnectorStyle,
      props.appearance.toolConnectorWidth,
      props.appearance.toolConnectorOpacity,
    ]
    if (measurementInputs.length > 0) props.layoutPort.invalidate('theme-changed')
  })

  onMount(() => {
    const unregister = props.layoutPort.registerConnector({
      key: props.connectorKey,
      fromMessageId: props.fromMessageId,
      toMessageId: props.toMessageId,
      measure: () => measureToolConnector(connector),
      apply(layout) {
        if (!connector) return
        connector.style.display = layout ? 'block' : 'none'
        if (!layout) return
        connector.style.left = `${layout.left}px`
        connector.style.top = `${layout.top}px`
        connector.style.height = `${layout.height}px`
      },
    })
    if (typeof ResizeObserver !== 'undefined' && connector) {
      observer = new ResizeObserver(() => props.layoutPort.invalidate('row-resized'))
      observer.observe(connector)
    }
    props.layoutPort.invalidate('items-changed')
    onCleanup(() => {
      observer?.disconnect()
      unregister()
    })
  })

  return (
    <div
      ref={connector}
      class={`term-tool-connector term-tool-connector-style--${props.appearance.toolConnectorStyle || 'solid'} ${toolConnectorMotionClass(state())}`}
      data-tool-state={state()}
      data-connector-mode={props.appearance.toolConnectorMode || 'fixed'}
      data-from-message-id={props.fromMessageId}
      data-to-message-id={props.toMessageId}
      style={{
        background: color(),
        '--tool-connector-color': color(),
        '--tool-connector-width': `${width()}px`,
        '--tool-connector-opacity': opacity(),
      }}
    />
  )
}

// src/components/chat/ToolConnector.tsx
import { memo } from 'react'
import { useStore } from '../../store'
import { resolveConnectorColor, type ToolConnectorStatus } from './toolPresentation'
import { toolConnectorMotionClass } from './toolIndicatorMotion'
import type { ToolVisualState } from '../../domains/tool/status.ts'

/**
 * 连续 Tool 之间的连接线（真实 DOM 元素）。
 * - 主界面：ChatView 渲染在行间，top/height 由测量 effect 写入。
 * - 预览（.pv-app）：无测量，top/height 由 CSS 公式提供。
 * - 层叠：线 z-index:1（body 背景之上、展开截断由测量控制），head z-index:2 盖线。
 * - 颜色和动画都继承连接线起点 Tool 的状态；mode none 时透明且无动画。
 */
function ToolConnector({ status, visualState = 'unknown' }: {
  status: ToolConnectorStatus
  visualState?: ToolVisualState
}) {
  const connectorMode = useStore(s => s.toolConnectorMode) || 'none'
  const connectorColor = useStore(s => s.toolConnectorColor) || 'rgba(0,0,0,0.12)'
  const toolOk = useStore(s => s.toolOk)
  const toolRun = useStore(s => s.toolRun)
  const toolErr = useStore(s => s.toolErr)
  const connectorStyle = useStore(s => s.toolConnectorStyle)
  const connectorWidth = useStore(s => s.toolConnectorWidth)
  const connectorOpacity = useStore(s => s.toolConnectorOpacity)
  const color = resolveConnectorColor(connectorMode, status, { toolOk, toolRun, toolErr }, connectorColor)
  const style: React.CSSProperties = {
    background: color,
    ['--tool-connector-color' as never]: color,
    ['--tool-connector-width' as never]: `${Math.max(1, Math.min(6, connectorWidth || 2))}px`,
    ['--tool-connector-opacity' as never]: Math.max(0.1, Math.min(1, connectorOpacity ?? 1)),
  }
  return (
    <div
      className={`term-tool-connector term-tool-connector-style--${connectorStyle || 'solid'} ${toolConnectorMotionClass(visualState)}`}
      data-tool-state={visualState}
      style={style}
    />
  )
}

// 连接线是 props + store 订阅的纯展示组件：ChatView 重渲染时跳过，主题变化仍即时生效
export default memo(ToolConnector)
