// src/components/right-panel/AgentContextPanel.tsx
import { useCallback, useEffect, useLayoutEffect, useMemo, useRef, useState, useSyncExternalStore, type Dispatch, type SetStateAction } from 'react'
import { FileCode2, Files, Search } from 'lucide-react'
import { useIdentityStore } from '../../domains/identity/identityStore'
import { useWorkspaceStore } from '../../domains/workspace/workspaceStore'
import { toAgentContextKey } from '../../domains/agent/agentContext'
import { sessionUiStateGet, sessionUiStateSet } from '../../domains/chat/sessionUiState'
import { searchValuesMatchQuery } from '../../domains/chat/messageSearchIndex'
import MessageSearchBar from './MessageSearchBar'
import type { SheetContext } from '../../workspace-sheets/sheetTypes'
import type { SheetRecord } from '../../workspace-sheets/sheetTypes'
import type { SessionUiKey } from '../../domains/workbench/sessionUiStore.ts'
import type { WorkbenchHostPort } from '../../plugin-runtime/renderers/workbenchHostPort.ts'
import {
  getActiveWorkbenchHostPort,
  subscribeActiveWorkbenchHostPort,
} from '../../sheets/agent-workbench/activeWorkbenchHostPort.ts'

/** 按会话作用域的 UI 状态钩子（自 domains/chat/sessionUiState 内联——唯一 React 消费点）。 */
function useSessionUiState<T,>(
  sessionId: string | null,
  key: string,
  initial: T,
): [T, Dispatch<SetStateAction<T>>] {
  const id = sessionId ?? ''
  const initialRef = useRef(initial)
  const [state, setState] = useState<T>(() => sessionUiStateGet<T>(id, key) ?? initialRef.current)
  // 会话切换：恢复该会话存档（useLayoutEffect 避免 B 先闪现 A 的一帧）
  useLayoutEffect(() => {
    setState(() => sessionUiStateGet<T>(id, key) ?? initialRef.current)
  }, [id, key])
  const set: Dispatch<SetStateAction<T>> = useCallback((action) => {
    setState(prev => {
      const next = typeof action === 'function' ? (action as (p: T) => T)(prev) : action
      sessionUiStateSet(id, key, next)
      return next
    })
  }, [id, key])
  return [state, set]
}

function useActiveWorkbenchHostPort(sheetId: string): WorkbenchHostPort | undefined {
  return useSyncExternalStore(
    useCallback(listener => subscribeActiveWorkbenchHostPort(sheetId, listener), [sheetId]),
    useCallback(() => getActiveWorkbenchHostPort(sheetId), [sheetId]),
    () => undefined,
  )
}

function useHostSessionUiState<T>(hostPort: WorkbenchHostPort | undefined, bindingKey: string | null, key: SessionUiKey, fallback: T): T {
  return useSyncExternalStore(
    useCallback(listener => bindingKey === null
      ? () => {}
      : hostPort?.sessionUi.subscribe(key, listener) ?? (() => {}), [bindingKey, hostPort, key]),
    useCallback(() => bindingKey === null
      ? fallback
      : hostPort?.sessionUi.get(key, fallback) ?? fallback, [bindingKey, fallback, hostPort, key]),
    () => fallback,
  )
}

function useHostDocument(hostPort: WorkbenchHostPort | undefined) {
  return useSyncExternalStore(
    useCallback(listener => hostPort?.document.subscribe(listener) ?? (() => {}), [hostPort]),
    useCallback(() => hostPort?.document.getSnapshot(), [hostPort]),
    () => undefined,
  )
}

/**
 * AgentContextPanel — agent 右栏（W2-12，F2-F）。
 *
 * 搜索模式：Renderer Suite 存在时消费当前 Sheet 发布的 Workbench Host Port，
 * 从 canonical document 计算命中并写 namespaced SessionUiPort；legacy ChatView
 * 仍通过原 sessionUiState/controller 回退，切换渲染模式不丢现有搜索能力。
 * 关联模式：touchedFiles 正向（会话→文件）。
 */
export default function AgentContextPanel({ sheet, ctx }: { sheet: SheetRecord; ctx: SheetContext }) {
  const sessionId = ctx.activeSession
  const source = ctx.sessionSource(sessionId)
  const hostPort = useActiveWorkbenchHostPort(sheet.id)
  const hostDocument = useHostDocument(hostPort)
  const [legacySearchQuery, setLegacySearchQuery] = useSessionUiState(sessionId, 'search-query', '')
  const [legacySearchIndex, setLegacySearchIndex] = useSessionUiState(sessionId, 'search-index', 0)
  const searchQuery = useHostSessionUiState(hostPort, sessionId, 'search-query', legacySearchQuery)
  const searchIndex = useHostSessionUiState(hostPort, sessionId, 'search-index', legacySearchIndex)
  const [mode, setMode] = useState<'search' | 'relations'>('search')
  const initializedHostBinding = useRef(false)
  const previousHostPort = useRef(hostPort)
  const previousSessionId = useRef(sessionId)

  useEffect(() => {
    const firstBinding = !initializedHostBinding.current
    initializedHostBinding.current = true
    const hostChanged = previousHostPort.current !== hostPort
    const sessionChanged = previousSessionId.current !== sessionId
    previousHostPort.current = hostPort
    previousSessionId.current = sessionId
    // Only bridge legacy state when a renderer Host appears for the same
    // session. A session switch must start from the new owner namespace.
    if (hostPort && sessionId && (firstBinding || hostChanged) && !sessionChanged) {
      if (hostPort.sessionUi.get<string | undefined>('search-query', undefined) === undefined) {
        hostPort.sessionUi.set('search-query', legacySearchQuery)
      }
      if (hostPort.sessionUi.get<number | undefined>('search-index', undefined) === undefined) {
        hostPort.sessionUi.set('search-index', legacySearchIndex)
      }
    }
  }, [hostPort, legacySearchIndex, legacySearchQuery, sessionId])

  // P52 D4：controller legacy 消息回退已退役——搜索命中只来自当前 Sheet 发布的
  // Workbench Host Port（canonical document）；无 Host Port 时无命中。
  const matches = useMemo(() => {
    if (!searchQuery.trim() || !hostPort) return []
    return (hostDocument?.messages ?? []).filter(message => searchValuesMatchQuery([
      message.source.provider,
      message.content,
      message.parts,
    ], searchQuery))
  }, [hostDocument, hostPort, searchQuery])
  const setSearchQuery = (value: string) => {
    setLegacySearchQuery(value)
    hostPort?.sessionUi.set('search-query', value)
  }
  const setSearchIndex = (valueOrUpdater: number | ((previous: number) => number)) => {
    const next = typeof valueOrUpdater === 'function' ? valueOrUpdater(searchIndex) : valueOrUpdater
    setLegacySearchIndex(next)
    hostPort?.sessionUi.set('search-index', next)
  }
  const moveSearch = (direction: 1 | -1) => {
    if (matches.length === 0) return
    setSearchIndex(index => (index + direction + matches.length) % matches.length)
  }
  // zustand v5 useStore 的 selector 返回值即 useSyncExternalStore 快照：`?? []` 每次返回
  // 新数组 → Object.is 不等 → forceStoreRerender 死循环。选整个 record（引用稳定），派生留组件体。
  // I01-W3：touchedFiles 按 AgentContextKey（agentId+source）隔离读取
  const touchedFilesRecord = useWorkspaceStore(s => s.touchedFiles)
  // CR-002：经 useIdentityStore selector 订阅（getState 不经订阅不响应变更）
  const touchedSession = useIdentityStore(state => sessionId
    ? state.sessions.find(item => item.id === sessionId)
    : undefined)
  const touchedContext = touchedSession && source
    ? { agentId: touchedSession.agentId, source: touchedSession.source }
    : null
  const touchedFiles = touchedContext ? touchedFilesRecord[toAgentContextKey(touchedContext)] ?? [] : []

  return (
    <div className="context-panel-contribution agent-context-panel">
      <div className="context-panel-subnav">
        <button type="button" aria-pressed={mode === 'search'} className={`context-panel-mode ${mode === 'search' ? 'active' : ''}`} onClick={() => setMode('search')}><Search size={14} aria-hidden="true" />搜索</button>
        <button type="button" aria-pressed={mode === 'relations'} className={`context-panel-mode ${mode === 'relations' ? 'active' : ''}`} onClick={() => setMode('relations')}><Files size={14} aria-hidden="true" />关联</button>
      </div>
      {mode === 'search' && (
        <MessageSearchBar
          query={searchQuery}
          matchIndex={searchIndex}
          matchCount={matches.length}
          onQueryChange={setSearchQuery}
          onPrevious={() => moveSearch(-1)}
          onNext={() => moveSearch(1)}
          onClose={() => { setSearchQuery(''); setSearchIndex(0) }}
        />
      )}
      {mode === 'search' && (!searchQuery.trim() || matches.length === 0) && (
        <div className="agent-context-empty flex flex-col items-start gap-3 p-4">
          <Search size={24} strokeWidth={1.5} aria-hidden="true" />
          <strong className="text-sm font-medium text-text">{searchQuery.trim() ? '没有匹配的消息' : '查找当前会话'}</strong>
          <p className="m-0 text-sm leading-relaxed text-text-dim">{searchQuery.trim() ? '尝试缩短关键词，或换一种表述。' : '输入关键词定位消息，使用 Enter / Shift+Enter 切换结果。'}</p>
        </div>
      )}
      {mode === 'relations' && (
        <div className="agent-relations">
          <div className="file-section-title">关联文件</div>
          {touchedFiles.length === 0 ? (
            <div className="agent-context-empty flex flex-col items-start gap-3 p-4"><Files size={24} strokeWidth={1.5} aria-hidden="true" /><p className="m-0 text-sm leading-relaxed text-text-dim">agent 尚未改动文件</p></div>
          ) : (
            <ul className="search-result-list">
              {touchedFiles.map(file => (
                <li key={`${file.path}:${file.at}`}>
                  <FileCode2 size={14} className="shrink-0 text-text-dim" aria-hidden="true" />
                  <span className="search-result-path min-w-0 break-all font-[family-name:var(--mono)]">{file.path}</span>
                </li>
              ))}
            </ul>
          )}
        </div>
      )}
    </div>
  )
}

// src/components/right-panel/AgentContextPanel.solid.tsx
/** @jsxImportSource solid-js */
import { createEffect, createMemo, createSignal, For, onCleanup, Show, type Accessor } from 'solid-js'
import { LucideIcon } from '../LucideIcon.solid.tsx'
import MessageSearchBar from './MessageSearchBar.solid.tsx'
import { createZustandSignal } from '../../host/solidStoreBridge.ts'
import { useIdentityStore } from '../../domains/identity/identityStore'
import { useWorkspaceStore } from '../../domains/workspace/workspaceStore'
import { toAgentContextKey } from '../../domains/agent/agentContext'
import { sessionUiStateGet, sessionUiStateSet } from '../../domains/chat/sessionUiState'
import { searchValuesMatchQuery } from '../../domains/chat/messageSearchIndex'
import type { SessionUiKey } from '../../domains/workbench/sessionUiStore.ts'
import type { WorkbenchDocument } from '../../domains/workbench/workbenchProjector.ts'
import type { WorkbenchHostPort } from '../../plugin-runtime/renderers/workbenchHostPort.ts'
import {
  getActiveWorkbenchHostPort,
  subscribeActiveWorkbenchHostPort,
} from '../../application/agent-workbench/activeWorkbenchHostPort.ts'
import type { AgentContextPanelProps } from './rightPanelTypes.ts'

/** 按会话作用域的 UI 状态（原 React 版 useSessionUiState 内联钩子的 Solid 形态）。 */
function createSessionUiState<T>(
  sessionId: () => string | null,
  key: string,
  initial: T,
): [Accessor<T>, (action: T | ((previous: T) => T)) => void] {
  const [state, setState] = createSignal<T>(sessionUiStateGet<T>(sessionId() ?? '', key) ?? initial)
  // 会话切换：恢复该会话存档（React 版用 useLayoutEffect 避免 B 先闪现 A 的一帧；
  // Solid 的 createEffect 在同一次渲染提交内读值，没有闪现窗口）。
  createEffect(() => {
    const id = sessionId() ?? ''
    // updater 形态：泛型 T 可能是函数值，走 (prev) => next 重载避开 Solid setter 的排除分支。
    setState(() => sessionUiStateGet<T>(id, key) ?? initial)
  })
  const set = (action: T | ((previous: T) => T)) => {
    setState(prev => {
      const next = typeof action === 'function' ? (action as (p: T) => T)(prev) : action
      sessionUiStateSet(sessionId() ?? '', key, next)
      return next
    })
  }
  return [state, set]
}

/** 当前 Sheet 发布的 Workbench Host Port（订阅随 sheetId 变化重挂）。 */
function createActiveWorkbenchHostPort(sheetId: () => string): Accessor<WorkbenchHostPort | undefined> {
  const [port, setPort] = createSignal<WorkbenchHostPort | undefined>(getActiveWorkbenchHostPort(sheetId()))
  createEffect(() => {
    const id = sheetId()
    setPort(getActiveWorkbenchHostPort(id))
    onCleanup(subscribeActiveWorkbenchHostPort(id, () => setPort(getActiveWorkbenchHostPort(id))))
  })
  return port
}

/** hostPort.sessionUi 的单键投影（bindingKey 为 null 时回落 fallback；fallback 变化重算）。 */
function createHostSessionUiValue<T>(
  hostPort: () => WorkbenchHostPort | undefined,
  bindingKey: () => string | null,
  key: SessionUiKey,
  fallback: () => T,
): Accessor<T> {
  const [value, setValue] = createSignal<T>(fallback())
  createEffect(() => {
    const port = hostPort()
    const id = bindingKey()
    const fb = fallback()
    // updater 形态：泛型 T 可能是函数值，走 (prev) => next 重载避开 Solid setter 的排除分支。
    setValue(() => (id === null ? fb : (port?.sessionUi.get<T>(key, fb) ?? fb)))
    if (id !== null && port) {
      onCleanup(port.sessionUi.subscribe(key, () => setValue(() => (port.sessionUi.get<T>(key, fb) ?? fb))))
    }
  })
  return value
}

/** hostPort.document 的快照投影（canonical document 变化即更新）。 */
function createHostDocument(hostPort: () => WorkbenchHostPort | undefined): Accessor<WorkbenchDocument | undefined> {
  const [document, setDocument] = createSignal<WorkbenchDocument | undefined>(hostPort()?.document.getSnapshot())
  createEffect(() => {
    const port = hostPort()
    setDocument(port?.document.getSnapshot())
    if (port) {
      onCleanup(port.document.subscribe(() => setDocument(port.document.getSnapshot())))
    }
  })
  return document
}

/**
 * AgentContextPanel — agent 右栏（W2-12，F2-F）。
 *
 * 搜索模式：Renderer Suite 存在时消费当前 Sheet 发布的 Workbench Host Port，
 * 从 canonical document 计算命中并写 namespaced SessionUiPort；legacy ChatView
 * 仍通过原 sessionUiState/controller 回退，切换渲染模式不丢现有搜索能力。
 * 关联模式：touchedFiles 正向（会话→文件）。
 */
export default function AgentContextPanel(props: AgentContextPanelProps) {
  const sessionId = () => props.ctx.activeSession
  const source = () => props.ctx.sessionSource(sessionId())
  const hostPort = createActiveWorkbenchHostPort(() => props.sheet.id)
  const hostDocument = createHostDocument(hostPort)
  const [legacySearchQuery, setLegacySearchQuery] = createSessionUiState(sessionId, 'search-query', '')
  const [legacySearchIndex, setLegacySearchIndex] = createSessionUiState(sessionId, 'search-index', 0)
  const searchQuery = createHostSessionUiValue(hostPort, sessionId, 'search-query', legacySearchQuery)
  const searchIndex = createHostSessionUiValue(hostPort, sessionId, 'search-index', legacySearchIndex)
  const [mode, setMode] = createSignal<'search' | 'relations'>('search')

  // Host 出现时把 legacy 会话状态桥接进 Host Port namespace。仅「同一会话上出现
  // （首个/更换的）Host」才桥；会话切换必须从新 owner namespace 起步。
  // （React 版用 ref 对比 first/hostChanged/sessionChanged，这里语义逐条对应。）
  let initializedHostBinding = false
  let previousHostPort: WorkbenchHostPort | undefined
  let previousSessionId: string | null = sessionId()
  createEffect(() => {
    const port = hostPort()
    const id = sessionId()
    const firstBinding = !initializedHostBinding
    initializedHostBinding = true
    const hostChanged = previousHostPort !== port
    const sessionChanged = previousSessionId !== id
    previousHostPort = port
    previousSessionId = id
    if (port && id && (firstBinding || hostChanged) && !sessionChanged) {
      if (port.sessionUi.get<string | undefined>('search-query', undefined) === undefined) {
        port.sessionUi.set('search-query', legacySearchQuery())
      }
      if (port.sessionUi.get<number | undefined>('search-index', undefined) === undefined) {
        port.sessionUi.set('search-index', legacySearchIndex())
      }
    }
  })

  // P52 D4：controller legacy 消息回退已退役——搜索命中只来自当前 Sheet 发布的
  // Workbench Host Port（canonical document）；无 Host Port 时无命中。
  const matches = createMemo(() => {
    const query = searchQuery()
    if (!query.trim() || !hostPort()) return []
    return (hostDocument()?.messages ?? []).filter(message => searchValuesMatchQuery([
      message.source.provider,
      message.content,
      message.parts,
    ], query))
  })
  const setSearchQuery = (value: string) => {
    setLegacySearchQuery(value)
    hostPort()?.sessionUi.set('search-query', value)
  }
  const setSearchIndex = (valueOrUpdater: number | ((previous: number) => number)) => {
    const next = typeof valueOrUpdater === 'function' ? valueOrUpdater(searchIndex()) : valueOrUpdater
    setLegacySearchIndex(next)
    hostPort()?.sessionUi.set('search-index', next)
  }
  const moveSearch = (direction: 1 | -1) => {
    if (matches().length === 0) return
    setSearchIndex(index => (index + direction + matches().length) % matches().length)
  }
  // I01-W3：touchedFiles 按 AgentContextKey（agentId+source）隔离读取。selector 不读
  // 组件局部响应式状态（solidStoreBridge ⚠️）：sessions 订阅在 store 侧，find 留在 memo。
  const touchedFilesRecord = createZustandSignal(useWorkspaceStore, s => s.touchedFiles)
  // CR-002：经订阅读 sessions（getState 不经订阅不响应变更）
  const identitySessions = createZustandSignal(useIdentityStore, s => s.sessions)
  const touchedFiles = createMemo(() => {
    const id = sessionId()
    const touchedSession = id ? identitySessions().find(item => item.id === id) : undefined
    const touchedSource = source()
    const touchedContext = touchedSession && touchedSource
      ? { agentId: touchedSession.agentId, source: touchedSource }
      : null
    return touchedContext ? touchedFilesRecord()[toAgentContextKey(touchedContext)] ?? [] : []
  })

  return (
    <div class="context-panel-contribution agent-context-panel">
      <div class="context-panel-subnav">
        <button type="button" aria-pressed={mode() === 'search'} class={`context-panel-mode ${mode() === 'search' ? 'active' : ''}`} onClick={() => setMode('search')}><LucideIcon name="Search" size={14} />搜索</button>
        <button type="button" aria-pressed={mode() === 'relations'} class={`context-panel-mode ${mode() === 'relations' ? 'active' : ''}`} onClick={() => setMode('relations')}><LucideIcon name="Files" size={14} />关联</button>
      </div>
      <Show when={mode() === 'search'}>
        <MessageSearchBar
          query={searchQuery()}
          matchIndex={searchIndex()}
          matchCount={matches().length}
          onQueryChange={setSearchQuery}
          onPrevious={() => moveSearch(-1)}
          onNext={() => moveSearch(1)}
          onClose={() => { setSearchQuery(''); setSearchIndex(0) }}
        />
      </Show>
      <Show when={mode() === 'search' && (!searchQuery().trim() || matches().length === 0)}>
        <div class="agent-context-empty flex flex-col items-start gap-3 p-4">
          <LucideIcon name="Search" size={24} strokeWidth={1.5} />
          <strong class="text-sm font-medium text-text">{searchQuery().trim() ? '没有匹配的消息' : '查找当前会话'}</strong>
          <p class="m-0 text-sm leading-relaxed text-text-dim">{searchQuery().trim() ? '尝试缩短关键词，或换一种表述。' : '输入关键词定位消息，使用 Enter / Shift+Enter 切换结果。'}</p>
        </div>
      </Show>
      <Show when={mode() === 'relations'}>
        <div class="agent-relations">
          <div class="file-section-title">关联文件</div>
          <Show when={touchedFiles().length === 0} fallback={
            <ul class="search-result-list">
              <For each={touchedFiles()}>{file => (
                <li>
                  <LucideIcon name="FileCode2" size={14} class="shrink-0 text-text-dim" />
                  <span class="search-result-path min-w-0 break-all font-[family-name:var(--mono)]">{file.path}</span>
                </li>
              )}</For>
            </ul>
          }>
            <div class="agent-context-empty flex flex-col items-start gap-3 p-4"><LucideIcon name="Files" size={24} strokeWidth={1.5} /><p class="m-0 text-sm leading-relaxed text-text-dim">agent 尚未改动文件</p></div>
          </Show>
        </div>
      </Show>
    </div>
  )
}
