// src/components/right-panel/RightRailHost.solid.tsx
/** @jsxImportSource solid-js */
import { createEffect, createMemo, createSignal, Show } from 'solid-js'
import { getContextPanelRegistry } from '../../plugin-runtime/runtimeServices.ts'
import { selectContextPanels, resolveContextPanelDefault } from '../../plugin-runtime/context-panel/contextPanelSelection.ts'
import { useRightRailStore, clampRightRailWidth, RIGHT_RAIL_MAX_WIDTH, RIGHT_RAIL_MIN_WIDTH } from '../../domains/workspace/layoutRailsStore.ts'
import ContextPanelHost from './ContextPanelHost.solid.tsx'
import { useThemeStore } from '../../domains/theme/themeStore.ts'
import { createBackgroundPresentation } from '../../infrastructure/skin/backgroundImage.ts'
import { createZustandSignal } from '../../infrastructure/state/solidStoreBridge.ts'
import { createRegistrySignal } from '../../infrastructure/state/solidSheetSupport.solid.tsx'
import type { SheetRecord } from '../../workspace-sheets/sheetTypes.ts'
import type { ShellContext } from '../../plugin-runtime/context-panel/contextPanelTypes.ts'
import type { RightRailHostProps } from './rightPanelTypes.ts'

const registry = getContextPanelRegistry()

const VIRTUAL_SHEET: SheetRecord = {
  id: 'right-rail-virtual', kind: 'overview', title: 'Workspace', createdAt: 0, lastFocusedAt: 0,
}

/** Application-level right rail host. Sheet context is input only; the rail
 * itself stays mounted while navigating between Sheets. */
export default function RightRailHost(props: RightRailHostProps) {
  const collapsed = createZustandSignal(useRightRailStore, state => state.collapsed)
  const width = createZustandSignal(useRightRailStore, state => state.width)
  const activePanelId = createZustandSignal(useRightRailStore, state => state.activePanelId)
  const backgroundImage = createZustandSignal(useThemeStore, state => state.rightBgImage)
  const background = createZustandSignal(useRightRailStore, state => state.background)
  const [dragWidth, setDragWidth] = createSignal<number | null>(null)
  const panelSnapshot = createRegistrySignal(registry, () => registry.getSnapshot())
  let dragRef: { pointerId: number; startX: number; startWidth: number } | null = null

  const shellContext = createMemo<ShellContext>(() => ({
    workspaceKind: props.sheet?.kind,
    sheetId: props.sheet?.id ?? null,
    activeSessionId: props.ctx.activeSession,
    activeAgent: props.activeAgent,
  }))
  // 面板清单**不再按 Sheet 种类过滤**（种类只决定默认选中谁）：用户显式选过的面板跨 Sheet 保持，
  // 没选过才回落到当前种类的亲和面板。见 `contextPanelSelection.ts`。
  const entries = createMemo(() => selectContextPanels(panelSnapshot().entries, shellContext()))
  const effectivePanelId = createMemo(() => entries().some(entry => entry.contributionId === activePanelId())
    ? activePanelId()
    : resolveContextPanelDefault(entries(), props.sheet?.kind)?.contributionId)

  // maxWidth 依赖 window.innerWidth：保持「读取时求值」，不缓存进 memo——
  // 窗口 resize 后的下一次渲染/拖拽拿到的都是新值。
  const maxWidth = () => Math.min(RIGHT_RAIL_MAX_WIDTH, Math.max(RIGHT_RAIL_MIN_WIDTH, window.innerWidth - 360))
  const renderedWidth = () => dragWidth() ?? width()

  createEffect(() => {
    const image = backgroundImage()
    if (!image) return
    const current = background()
    if (current?.src === image) return
    useRightRailStore.getState().setBackground(createBackgroundPresentation(image, width(), current?.sizing ?? 'fill'))
  })

  const cancelDrag = () => {
    dragRef = null
    setDragWidth(null)
  }

  return (
    <Show when={entries().length > 0}>
      {/* Keep the rail mounted while collapsed. The application-level host owns
          the rail lifetime; retaining the DOM lets the shell animate its width and
          preserves an active panel's local state across a collapse/expand cycle. */}
      <div
        class={`right-rail-host${collapsed() ? ' is-collapsed' : ''}${dragWidth() !== null ? ' is-resizing' : ''}`}
        data-collapsed={collapsed() ? 'true' : 'false'}
        aria-hidden={collapsed() ? 'true' : undefined}
        data-background-sizing={background()?.sizing ?? 'fill'}
        style={{
          '--right-rail-width': `${Math.min(renderedWidth(), maxWidth())}px`,
          '--right-bg-image': background()?.src ? `url(${JSON.stringify(background()!.src)})` : 'var(--right-bg-image, none)',
        }}
      >
        <div
          class="right-rail-resize-handle"
          role="separator"
          aria-orientation="vertical"
          aria-valuemin={RIGHT_RAIL_MIN_WIDTH}
          aria-valuemax={maxWidth()}
          aria-valuenow={Math.min(renderedWidth(), maxWidth())}
          tabIndex={collapsed() ? -1 : 0}
          onPointerDown={event => {
            if (collapsed() || event.button !== 0 || dragRef) return
            event.preventDefault()
            dragRef = { pointerId: event.pointerId, startX: event.clientX, startWidth: Math.min(width(), maxWidth()) }
            setDragWidth(Math.min(width(), maxWidth()))
            event.currentTarget.setPointerCapture?.(event.pointerId)
          }}
          onPointerMove={event => {
            const drag = dragRef
            if (!drag || drag.pointerId !== event.pointerId) return
            if (collapsed()) { cancelDrag(); return }
            setDragWidth(Math.min(maxWidth(), clampRightRailWidth(drag.startWidth + drag.startX - event.clientX)))
          }}
          onPointerUp={event => {
            const drag = dragRef
            if (!drag || drag.pointerId !== event.pointerId) return
            if (!collapsed()) useRightRailStore.getState().setWidth(Math.min(maxWidth(), clampRightRailWidth(drag.startWidth + drag.startX - event.clientX)))
            cancelDrag()
          }}
          onPointerCancel={event => { if (dragRef?.pointerId === event.pointerId) cancelDrag() }}
          onLostPointerCapture={event => { if (dragRef?.pointerId === event.pointerId) cancelDrag() }}
          onKeyDown={event => {
            if (event.key === 'ArrowLeft' || event.key === 'ArrowRight') {
              event.preventDefault()
              useRightRailStore.getState().setWidth(clampRightRailWidth(width() + (event.key === 'ArrowLeft' ? 8 : -8)))
            } else if (event.key === 'Home') useRightRailStore.getState().setWidth(RIGHT_RAIL_MIN_WIDTH)
            else if (event.key === 'End') useRightRailStore.getState().setWidth(maxWidth())
          }}
          aria-label="调整右侧栏宽度"
        />
        <ContextPanelHost sheet={props.sheet ?? VIRTUAL_SHEET} ctx={props.ctx} activePanelId={effectivePanelId()} />
      </div>
    </Show>
  )
}

// src/components/right-panel/RightRailHost.tsx
import { useEffect, useMemo, useRef, useState, useSyncExternalStore, type CSSProperties } from 'react'
import type { SheetContext, SheetRecord } from '../../workspace-sheets/sheetTypes.ts'
import { getContextPanelRegistry } from '../../plugin-runtime/runtimeServices.ts'
import { selectContextPanels, resolveContextPanelDefault } from '../../plugin-runtime/context-panel/contextPanelSelection.ts'
import { useRightRailStore, clampRightRailWidth, RIGHT_RAIL_MAX_WIDTH, RIGHT_RAIL_MIN_WIDTH } from '../../domains/workspace/layoutRailsStore.ts'
import ContextPanelHost from './ContextPanelHost.tsx'
import { useStore } from '../../domains/theme/themeStore.ts'
import { createBackgroundPresentation } from '../../infrastructure/skin/backgroundImage.ts'

const registry = getContextPanelRegistry()
const subscribe = (listener: () => void) => registry.subscribe(listener)
const snapshot = () => registry.getSnapshot()

const VIRTUAL_SHEET: SheetRecord = {
  id: 'right-rail-virtual', kind: 'overview', title: 'Workspace', createdAt: 0, lastFocusedAt: 0,
}

/** Application-level right rail host. Sheet context is input only; the rail
 * itself stays mounted while navigating between Sheets. */
export default function RightRailHost({ sheet, ctx, activeAgent }: { sheet: SheetRecord | null; ctx: SheetContext; activeAgent?: string }) {
  const collapsed = useRightRailStore(state => state.collapsed)
  const width = useRightRailStore(state => state.width)
  const activePanelId = useRightRailStore(state => state.activePanelId)
  const backgroundImage = useStore(state => state.rightBgImage)
  const background = useRightRailStore(state => state.background)
  const setWidth = useRightRailStore(state => state.setWidth)
  const setBackground = useRightRailStore(state => state.setBackground)
  const [dragWidth, setDragWidth] = useState<number | null>(null)
  const dragRef = useRef<{ pointerId: number; startX: number; startWidth: number } | null>(null)
  const panelSnapshot = useSyncExternalStore(subscribe, snapshot, snapshot)
  const shellContext = useMemo(() => ({
    workspaceKind: sheet?.kind,
    sheetId: sheet?.id ?? null,
    activeSessionId: ctx.activeSession,
    activeAgent,
  }), [sheet?.kind, sheet?.id, ctx.activeSession, activeAgent])
  // 面板清单**不再按 Sheet 种类过滤**（种类只决定默认选中谁）：用户显式选过的面板跨 Sheet 保持，
  // 没选过才回落到当前种类的亲和面板。见 `contextPanelSelection.ts`。
  const entries = useMemo(() => selectContextPanels(panelSnapshot.entries, shellContext), [panelSnapshot, shellContext])
  const effectivePanelId = entries.some(entry => entry.contributionId === activePanelId)
    ? activePanelId
    : resolveContextPanelDefault(entries, sheet?.kind)?.contributionId

  useEffect(() => {
    if (!backgroundImage) return
    if (background?.src === backgroundImage) return
    setBackground(createBackgroundPresentation(backgroundImage, width, background?.sizing ?? 'fill'))
  }, [backgroundImage, background?.src, background?.sizing, setBackground, width])

  const cancelDrag = () => {
    dragRef.current = null
    setDragWidth(null)
  }

  // Keep the rail mounted while collapsed. The application-level host owns
  // the rail lifetime; retaining the DOM lets the shell animate its width and
  // preserves an active panel's local state across a collapse/expand cycle.
  if (entries.length === 0) return null
  const activeSheet = sheet ?? VIRTUAL_SHEET
  const renderedWidth = dragWidth ?? width
  const maxWidth = Math.min(RIGHT_RAIL_MAX_WIDTH, Math.max(RIGHT_RAIL_MIN_WIDTH, window.innerWidth - 360))
  return (
    <div className={`right-rail-host${collapsed ? ' is-collapsed' : ''}${dragWidth !== null ? ' is-resizing' : ''}`} data-collapsed={collapsed ? 'true' : 'false'} aria-hidden={collapsed ? 'true' : undefined} data-background-sizing={background?.sizing ?? 'fill'} style={{ '--right-rail-width': `${Math.min(renderedWidth, maxWidth)}px`, '--right-bg-image': background?.src ? `url(${JSON.stringify(background.src)})` : 'var(--right-bg-image, none)' } as CSSProperties}>
      <div
        className="right-rail-resize-handle"
        role="separator"
        aria-orientation="vertical"
        aria-valuemin={RIGHT_RAIL_MIN_WIDTH}
        aria-valuemax={maxWidth}
        aria-valuenow={Math.min(renderedWidth, maxWidth)}
        tabIndex={collapsed ? -1 : 0}
        onPointerDown={event => {
          if (collapsed || event.button !== 0 || dragRef.current) return
          event.preventDefault()
          dragRef.current = { pointerId: event.pointerId, startX: event.clientX, startWidth: Math.min(width, maxWidth) }
          setDragWidth(Math.min(width, maxWidth))
          event.currentTarget.setPointerCapture?.(event.pointerId)
        }}
        onPointerMove={event => {
          const drag = dragRef.current
          if (!drag || drag.pointerId !== event.pointerId) return
          if (collapsed) { cancelDrag(); return }
          setDragWidth(Math.min(maxWidth, clampRightRailWidth(drag.startWidth + drag.startX - event.clientX)))
        }}
        onPointerUp={event => {
          const drag = dragRef.current
          if (!drag || drag.pointerId !== event.pointerId) return
          if (!collapsed) setWidth(Math.min(maxWidth, clampRightRailWidth(drag.startWidth + drag.startX - event.clientX)))
          cancelDrag()
        }}
        onPointerCancel={event => { if (dragRef.current?.pointerId === event.pointerId) cancelDrag() }}
        onLostPointerCapture={event => { if (dragRef.current?.pointerId === event.pointerId) cancelDrag() }}
        onKeyDown={event => {
          if (event.key === 'ArrowLeft' || event.key === 'ArrowRight') {
            event.preventDefault()
            setWidth(clampRightRailWidth(width + (event.key === 'ArrowLeft' ? 8 : -8)))
          } else if (event.key === 'Home') setWidth(RIGHT_RAIL_MIN_WIDTH)
          else if (event.key === 'End') setWidth(maxWidth)
        }}
        aria-label="调整右侧栏宽度"
      />
      <ContextPanelHost sheet={activeSheet} ctx={ctx} activePanelId={effectivePanelId} />
    </div>
  )
}
