// src/workspace-sheets/SheetErrorBoundary.solid.tsx
/** @jsxImportSource solid-js */
import { reportRuntimeDiagnostic, resolveRuntimeErrors } from '../app/runtimeError.ts'
import { ErrorBoundary, type JSX } from 'solid-js'

interface SheetErrorBoundaryProps { children: JSX.Element; sheetId: string }

/**
 * SheetErrorBoundary — Sheet 级错误隔离（报告 8.2）。
 *
 * 单个 Sheet 渲染异常只隔离自身（retry/reset），不拖垮整个应用
 * （应用级边界由 KernelRoot.solid 兜底）。#515：React class 边界 → solid ErrorBoundary，
 * fallback DOM（role=alert / 类名 / 按钮文案）逐字节保持。
 */
export default function SheetErrorBoundary(props: SheetErrorBoundaryProps) {
  // componentDidCatch 语义：每个错误实例只报一次（fallback 函数可能随响应式更新重跑）。
  let reported: unknown
  return (
    <ErrorBoundary fallback={(error, reset) => {
      if (reported !== error) {
        reported = error
        reportRuntimeDiagnostic('Sheet 渲染失败', error, undefined, {
          key: `sheet-render:${props.sheetId}`,
          scope: { kind: 'sheet', id: props.sheetId },
          source: 'sheet.boundary',
        })
      }
      return (
        <div class="sheet-empty-host" role="alert">
          <div class="sheet-empty-kicker">SHEET ERROR</div>
          <h2>此 Sheet 渲染失败</h2>
          <p>{error.message}</p>
          <button type="button" class="template-apply" onClick={() => {
            resolveRuntimeErrors({ key: `sheet-render:${props.sheetId}` })
            reset()
          }}>重试</button>
        </div>
      )
    }}>
      {props.children}
    </ErrorBoundary>
  )
}

// src/workspace-sheets/SheetErrorBoundary.tsx
import { Component, type ErrorInfo, type ReactNode } from 'react'
import { reportRuntimeDiagnostic, resolveRuntimeErrors } from '../app/runtimeError.ts'

interface Props { children: ReactNode; sheetId: string }
interface State { error: Error | null }

/**
 * SheetErrorBoundary — Sheet 级错误隔离（报告 8.2）。
 *
 * 单个 Sheet 渲染异常只隔离自身（retry/reset），不拖垮整个应用
 * （应用级 ErrorBoundary 仍由 main.tsx 兜底）。
 */
export default class SheetErrorBoundary extends Component<Props, State> {
  state: State = { error: null }

  static getDerivedStateFromError(error: Error): State { return { error } }

  componentDidCatch(error: Error, _info: ErrorInfo) {
    // The blocking Sheet fallback is already the authoritative presentation.
    // Keep the technical fact queryable without creating a second global tray
    // notification for the same crash.
    reportRuntimeDiagnostic('Sheet 渲染失败', error, undefined, {
      key: `sheet-render:${this.props.sheetId}`,
      scope: { kind: 'sheet', id: this.props.sheetId },
      source: 'sheet.boundary',
    })
  }

  render() {
    if (this.state.error) {
      return (
        <div className="sheet-empty-host" role="alert">
          <div className="sheet-empty-kicker">SHEET ERROR</div>
          <h2>此 Sheet 渲染失败</h2>
          <p>{this.state.error.message}</p>
          <button type="button" className="template-apply" onClick={() => {
            resolveRuntimeErrors({ key: `sheet-render:${this.props.sheetId}` })
            this.setState({ error: null })
          }}>重试</button>
        </div>
      )
    }
    return this.props.children
  }
}
