// src/sheets/file/FileSheetSidebar.tsx
import { Clock3, Files, GitBranch, MessageSquare, Search } from 'lucide-react'
import type { FileActivityContribution } from '../../plugin-runtime/file-workbench/fileWorkbenchTypes.ts'

/** FileSheetSidebar — 固定宽度轨道；折叠只隐藏 Explorer 内容，Activity Bar 保持可用。 */
export default function FileSheetSidebar({
  activeSection,
  activities,
  collapsed,
  onSelectSection,
  children,
}: {
  activeSection: string
  activities: readonly FileActivityContribution[]
  collapsed: boolean
  onSelectSection: (section: string) => void
  children?: React.ReactNode
}) {
  const icons: Record<FileActivityContribution['icon'], React.ReactNode> = {
    sessions: <MessageSquare size={21} />,
    files: <Files size={21} />,
    search: <Search size={21} />,
    scm: <GitBranch size={21} />,
    views: <Clock3 size={21} />,
  }
  const selected = activities.find(activity => activity.id === activeSection) ?? activities[0]

  // I09-A-FE-02：折叠由 titlebar 统一控制（ctx.sidebarCollapsed），点击分区图标不再触发展开/收起
  const selectSection = (section: string) => {
    onSelectSection(section)
  }

  return (
    <aside className={`file-sidebar ${collapsed ? 'collapsed' : ''}`}>
      <nav className="file-activity-bar" aria-label="FileSheet 分区">
        {activities.map(activity => (
          <button
            key={activity.id}
            type="button"
            className={`file-activity-item ${activeSection === activity.id ? 'active' : ''}`}
            onClick={() => selectSection(activity.id)}
            title={`${activity.label}：${activity.description}`}
            aria-label={`${activity.label}：${activity.description}`}
          >
            <span className="file-activity-icon" aria-hidden="true">{icons[activity.icon]}</span>
          </button>
        ))}
      </nav>

      {!collapsed && (
        <div className="file-sidebar-panel">
          <header className="file-sidebar-header">
            <div>
              <span className="file-sidebar-kicker">{selected?.label ?? '能力不可用'}</span>
              <strong>{selected?.description ?? '插件已停用，请选择其他分区'}</strong>
            </div>
          </header>

          <div className="file-section-content">{children}</div>
        </div>
      )}
    </aside>
  )
}

// src/sheets/file/FileSheetSidebar.solid.tsx
import { For, Show, type JSX } from 'solid-js'
import type { FileActivityContribution } from '../../plugin-runtime/file-workbench/fileWorkbenchTypes.ts'
import { WorkbenchIcon } from './fileIcons.solid.tsx'

/**
 * FileSheetSidebarProps — 与 React 原件（FileSheetSidebar.tsx）逐字段一致。
 */
export interface FileSheetSidebarProps {
  activeSection: string
  activities: readonly FileActivityContribution[]
  collapsed: boolean
  onSelectSection: (section: string) => void
  children?: JSX.Element
}

const ICON_NAMES: Record<FileActivityContribution['icon'], string> = {
  sessions: 'MessageSquare',
  files: 'Files',
  search: 'Search',
  scm: 'GitBranch',
  views: 'Clock3',
}

/**
 * FileSheetSidebar — 左列内容（#154：宽度/竖直分割线/折叠可见性归布局层的 .sidebar）。
 * #515 Solid 实体；React 原件保留在 FileSheetSidebar.tsx（唯一消费者 FileSheetView 已
 * 直连本实体；原件随批7 退役）。
 */
export default function FileSheetSidebar(props: FileSheetSidebarProps) {
  const selected = () => props.activities.find(activity => activity.id === props.activeSection) ?? props.activities[0]

  // I09-A-FE-02：折叠由 titlebar 统一控制（ctx.sidebarCollapsed），点击分区图标不再触发展开/收起
  const selectSection = (section: string) => {
    props.onSelectSection(section)
  }

  return (
    <aside class="sidebar file-sidebar">
      <nav class="file-activity-bar" aria-label="FileSheet 分区">
        <For each={props.activities}>{activity => (
          <button
            type="button"
            class={`file-activity-item ${props.activeSection === activity.id ? 'active' : ''}`}
            onClick={() => selectSection(activity.id)}
            title={`${activity.label}：${activity.description}`}
            aria-label={`${activity.label}：${activity.description}`}
          >
            <span class="file-activity-icon" aria-hidden="true">
              <WorkbenchIcon name={ICON_NAMES[activity.icon]} size={21} />
            </span>
          </button>
        )}</For>
      </nav>

      <Show when={!props.collapsed}>
        <div class="file-sidebar-panel">
          <header class="file-sidebar-header">
            <div>
              <span class="file-sidebar-kicker">{selected()?.label ?? '能力不可用'}</span>
              <strong>{selected()?.description ?? '插件已停用，请选择其他分区'}</strong>
            </div>
          </header>

          <div class="file-section-content">{props.children}</div>
        </div>
      </Show>
    </aside>
  )
}
