// src/sheets/file/FileTabBar.solid.tsx
import { For, Show } from 'solid-js'
import { fileTabKey, fileTabViewType, type FileTabRecord } from './fileSheetState.ts'

/**
 * FileTabBarProps — 与 React 原件（FileTabBar.tsx）逐字段一致。
 */
export interface FileTabBarProps {
  tabs: readonly FileTabRecord[]
  activeKey: string | null
  dirtyKeys?: ReadonlySet<string>
  savingKeys?: ReadonlySet<string>
  onSelect: (key: string) => void
  onClose: (key: string) => void
}

/**
 * FileTabBar — 版本化 tab 条（ISSUE-08 D-02/D-04；#515 Solid 实体）。
 *
 * tabs/activeKey 存 sheet metadata（`{version:2,tabs:[{path,mode,staged?}],activeKey}`，
 * 可序列化、重启恢复）。tab 单例 key = `${mode}:${path}`：同路径 file/diff 并存为
 * 两个 tab 且不互相覆盖；关闭/切换均以 key 回调 FileSheetView 的 patchSheetMetadata。
 * React 原件保留在 FileTabBar.tsx（唯一消费者 FileSheetView 已直连本实体；原件随批7 退役）。
 */
export default function FileTabBar(props: FileTabBarProps) {
  return (
    <Show when={props.tabs.length > 0}>
      <div class="file-tab-bar" role="tablist" aria-label="已打开文件">
        <For each={props.tabs}>{tab => {
          const key = fileTabKey(tab)
          const isDiff = fileTabViewType(tab) === 'git.diff'
          const label = isDiff ? `${tab.path}（diff）` : tab.path
          const dirty = () => props.dirtyKeys?.has(key) === true
          const saving = () => props.savingKeys?.has(key) === true
          return (
            <span
              role="tab"
              aria-selected={props.activeKey === key}
              class={`file-tab ${props.activeKey === key ? 'active' : ''} ${isDiff ? 'file-tab-diff' : ''} ${dirty() ? 'dirty' : ''} ${saving() ? 'saving' : ''}`}
              data-dirty={dirty() ? 'true' : undefined}
              data-saving={saving() ? 'true' : undefined}
              onClick={() => props.onSelect(key)}
              title={label}
            >
              <span class="file-tab-name">{tab.path.split('/').pop()}</span>
              <Show when={isDiff}><span class="file-tab-mode">{tab.staged ? 'staged' : 'unstaged'}</span></Show>
              <Show when={saving()} fallback={
                <Show when={dirty()}>
                  <span class="file-tab-state dirty" role="status" aria-label={`未保存 ${label}`}>●</span>
                </Show>
              }>
                <span class="file-tab-state saving" role="status" aria-label={`正在保存 ${label}`}>…</span>
              </Show>
              <button
                type="button"
                class="file-tab-close"
                aria-label={`关闭 ${label}`}
                disabled={saving()}
                onClick={event => { event.stopPropagation(); props.onClose(key) }}
              >
                ✕
              </button>
            </span>
          )
        }}</For>
      </div>
    </Show>
  )
}

// src/sheets/file/FileTabBar.tsx
import { fileTabKey, fileTabViewType, type FileTabRecord } from './fileSheetState.ts'

/**
 * FileTabBar — 版本化 tab 条（ISSUE-08 D-02/D-04）。
 *
 * tabs/activeKey 存 sheet metadata（`{version:2,tabs:[{path,mode,staged?}],activeKey}`，
 * 可序列化、重启恢复）。tab 单例 key = `${mode}:${path}`：同路径 file/diff 并存为
 * 两个 tab 且不互相覆盖；关闭/切换均以 key 回调 FileSheetView 的 patchSheetMetadata。
 */
export default function FileTabBar({ tabs, activeKey, dirtyKeys, savingKeys, onSelect, onClose }: {
  tabs: readonly FileTabRecord[]
  activeKey: string | null
  dirtyKeys?: ReadonlySet<string>
  savingKeys?: ReadonlySet<string>
  onSelect: (key: string) => void
  onClose: (key: string) => void
}) {
  if (tabs.length === 0) return null
  return (
    <div className="file-tab-bar" role="tablist" aria-label="已打开文件">
      {tabs.map(tab => {
        const key = fileTabKey(tab)
        const isDiff = fileTabViewType(tab) === 'git.diff'
        const label = isDiff ? `${tab.path}（diff）` : tab.path
        const dirty = dirtyKeys?.has(key) === true
        const saving = savingKeys?.has(key) === true
        return (
          <span
            key={key}
            role="tab"
            aria-selected={activeKey === key}
            className={`file-tab ${activeKey === key ? 'active' : ''} ${isDiff ? 'file-tab-diff' : ''} ${dirty ? 'dirty' : ''} ${saving ? 'saving' : ''}`}
            data-dirty={dirty ? 'true' : undefined}
            data-saving={saving ? 'true' : undefined}
            onClick={() => onSelect(key)}
            title={label}
          >
            <span className="file-tab-name">{tab.path.split('/').pop()}</span>
            {isDiff && <span className="file-tab-mode">{tab.staged ? 'staged' : 'unstaged'}</span>}
            {saving
              ? <span className="file-tab-state saving" role="status" aria-label={`正在保存 ${label}`}>…</span>
              : dirty
                ? <span className="file-tab-state dirty" role="status" aria-label={`未保存 ${label}`}>●</span>
                : null}
            <button
              type="button"
              className="file-tab-close"
              aria-label={`关闭 ${label}`}
              disabled={saving}
              onClick={event => { event.stopPropagation(); onClose(key) }}
            >
              ✕
            </button>
          </span>
        )
      })}
    </div>
  )
}
