// src/sheets/file/MarkdownPreview.solid.tsx
import { createEffect, createSignal, onCleanup, Show } from 'solid-js'
import { render } from 'solid-js/web'
import {
  loadMarkdownCompute,
  type MarkdownModelElement,
  type MarkdownModelNode,
  type MarkdownModelRoot,
} from '../../infrastructure/compute/markdownCompute.ts'
import { reportRuntimeError } from '../../runtimeError.ts'

// hast 语义属性名（camelCase）→ Solid 属性名：aria/data 家族需连字符小写化；
// className 数组拍平为 class；checked/value 原样（Solid 无受控告警概念，非受控投影
// 的 React 侧特判在此不适用）。
function toDashCase(name: string): string {
  return name.replace(/[A-Z]/g, character => `-${character.toLowerCase()}`)
}

function modelPropertiesToElementProps(properties: MarkdownModelElement['properties']): Record<string, unknown> {
  const elementProps: Record<string, unknown> = {}
  for (const [name, value] of Object.entries(properties)) {
    if (value === undefined || value === null) continue
    if (name === 'className') {
      const className = Array.isArray(value) ? value.join(' ') : String(value)
      if (className !== '') elementProps.class = className
    } else if (/^(?:aria|data)[A-Z]/.test(name)) {
      elementProps[toDashCase(name)] = value
    } else {
      elementProps[name] = value
    }
  }
  return elementProps
}

// comrak 的容器排版会在 blockquote/ul/ol/table 家族子级插入 `"\n"` 分隔文本节点；
// 它们在块级子元素之间无排版语义，投影时剔除（段内软换行在文本 value 内部，不受影响）。
function isContainerSeparator(node: MarkdownModelNode): boolean {
  return node.type === 'text' && node.value === '\n'
}

/**
 * 模型 → DOM 直绘投影：解析产物是每次落地即冻结的静态树（模型级缓存持有），无需
 * 响应式插入，直接 createElement/setAttribute 即可。属性语义与 React 版投影一致：
 * class 拍平、aria/data 连字符化、布尔属性按空值属性呈现、href/src/align 原样。
 */
function renderModelDom(node: MarkdownModelNode): Node {
  if (node.type === 'text') return document.createTextNode(node.value)
  const element = document.createElement(node.tagName)
  for (const [name, value] of Object.entries(modelPropertiesToElementProps(node.properties))) {
    if (name === 'class') element.setAttribute('class', String(value))
    // 布尔 true 落 "true" 值属性（对齐 React 版 data-footnote-ref="true" 的形状契约）；
    // 布尔 false 不落属性（checked="false" 在 HTML 语义里仍为真）
    else if (value === true) element.setAttribute(name, 'true')
    else if (value === false) continue
    else element.setAttribute(name, String(value))
  }
  for (const child of node.children) {
    if (!isContainerSeparator(child)) element.appendChild(renderModelDom(child))
  }
  return element
}

export interface MarkdownPreviewProps {
  /** 响应式：text 变化触发重解析（保留旧模型直到新解析落地，避免加载态闪烁）。 */
  latest: () => { text: string }
}

/**
 * FileTabView markdown 文件预览的 Solid 实体（#279 第 2 梯队）。
 *
 * 解析统一走 wasm 计算核（`parseMarkdown`，comrak），与聊天主链路同一实现。装载是
 * 异步的；完成前渲染加载态。文本变化时保留旧模型直到新解析落地。失败经
 * `reportRuntimeError` 上报 + 失败态文案，不吞错。
 */
export default function MarkdownPreview(p: MarkdownPreviewProps) {
  const [model, setModel] = createSignal<MarkdownModelRoot | null>(null)
  const [failed, setFailed] = createSignal(false)

  createEffect(() => {
    const text = p.latest().text
    let cancelled = false
    loadMarkdownCompute()
      .then(compute => compute.parseMarkdown(text) as MarkdownModelRoot)
      .then(parsed => {
        if (cancelled) return
        setFailed(false)
        setModel(parsed)
      })
      .catch(error => {
        if (cancelled) return
        setFailed(true)
        setModel(null)
        reportRuntimeError('渲染 Markdown', error, undefined, {
          scope: { kind: 'sheet', id: 'file-tab:markdown-preview' },
          source: 'file.tab',
        })
      })
    onCleanup(() => { cancelled = true })
  })

  let hostElement: HTMLDivElement | undefined

  createEffect(() => {
    const root = model()
    if (!hostElement) return
    if (!root) { hostElement.replaceChildren(); return }
    hostElement.replaceChildren(...root.children.filter(node => !isContainerSeparator(node)).map(renderModelDom))
  })

  return (
    <Show when={!failed()} fallback={<p class="file-tab-hint">Markdown 渲染失败，详情见右下角错误中心</p>}>
      <Show when={model()} fallback={<p class="file-tab-hint">加载 Markdown…</p>}>
        <div ref={element => { hostElement = element }} />
      </Show>
    </Show>
  )
}

/** React 薄桥（MarkdownPreview.tsx）的挂载工厂：Solid JSX 只允许出现在本文件。 */
export function renderMarkdownPreview(container: HTMLElement, latest: () => { text: string }): () => void {
  return render(() => <MarkdownPreview latest={latest} />, container)
}

// src/sheets/file/MarkdownPreview.tsx
import { createElement, useEffect, useState, type ReactNode } from 'react'
import {
  loadMarkdownCompute,
  type MarkdownModelElement,
  type MarkdownModelNode,
  type MarkdownModelRoot,
} from '../../infrastructure/compute/markdownCompute.ts'
import { reportRuntimeError } from '../../runtimeError.ts'

// hast 语义属性名（camelCase）→ React 属性名：aria/data 家族需连字符小写化
// （React 对驼峰的自定义属性会原样小写展开，`dataFootnoteRef` 会丢中段），其余透传。
function toDashCase(name: string): string {
  return name.replace(/[A-Z]/g, character => `-${character.toLowerCase()}`)
}

// React 对「有 checked/value 却无 onChange」的受控表单字段会告警（测试侧 console.error
// 白名单硬断言会拦）。文件预览的复选框/字段是纯展示，按非受控投影。
const UNCONTROLLED_FORM_PROPS = new Set(['checked', 'value'])

function modelPropertiesToReactProps(properties: MarkdownModelElement['properties']): Record<string, unknown> {
  const reactProps: Record<string, unknown> = {}
  for (const [name, value] of Object.entries(properties)) {
    if (value === undefined || value === null) continue
    if (name === 'className') {
      const className = Array.isArray(value) ? value.join(' ') : String(value)
      if (className !== '') reactProps.className = className
    } else if (UNCONTROLLED_FORM_PROPS.has(name)) {
      reactProps[name === 'checked' ? 'defaultChecked' : 'defaultValue'] = value
    } else if (/^(?:aria|data)[A-Z]/.test(name)) {
      reactProps[toDashCase(name)] = value
    } else {
      reactProps[name] = value
    }
  }
  return reactProps
}

// 通用投影，不做逐标签特判：文件预览没有聊天路径的 term-* 表现层（锚点 id、
// MathRender、代码高亮等原 react-markdown 路径同样没有），`.file-tab-md` 容器样式
// 消费的正是这份裸元素流。
// comrak 的容器排版会在 blockquote/ul/ol/table/thead/tbody/tr 的子级插入 `"\n"`
// 分隔文本节点（parser.rs「容器 \n 排版」）。React 对 table 家族容器内的纯空白
// 文本节点会发 dev 告警（撞测试白名单硬断言），且它们在块级子元素之间无排版
// 语义——投影时剔除；段内软换行在文本 value 内部，不受影响。
function isContainerSeparator(node: MarkdownModelNode): boolean {
  return node.type === 'text' && node.value === '\n'
}

function renderModelNode(node: MarkdownModelNode, key: number): ReactNode {
  if (node.type === 'text') return node.value
  if (node.type === 'element') {
    const children = renderModelNodes(node.children)
    // void 元素（img/hr/br…，模型中 children 恒空）不得带 children 形参——React 对
    // 空数组同样按「void 元素带 children」抛错。
    return createElement(
      node.tagName,
      { ...modelPropertiesToReactProps(node.properties), key },
      children.length > 0 ? children : undefined,
    )
  }
  return null
}

function renderModelNodes(nodes: readonly MarkdownModelNode[]): ReactNode[] {
  return nodes.filter(node => !isContainerSeparator(node)).map(renderModelNode)
}

type MarkdownPreviewState =
  | { status: 'loading' }
  | { status: 'ready'; model: MarkdownModelRoot }
  | { status: 'error' }

/**
 * FileTabView markdown 文件预览的渲染器（#276）。
 *
 * 解析统一走 wasm 计算核（`parseMarkdown`，comrak），与聊天主链路同一实现——
 * 取代原 react-markdown + remark-gfm 的 lazy 路径（markdownLazy.tsx 已随 #276 删除）。
 * 装载是异步的；完成前渲染加载态（承接原 Suspense fallback 的可见行为）。文本变化时
 * 保留旧模型直到新解析落地（解析是毫秒级同步计算，避免加载态闪烁）。
 */
export function MarkdownPreview({ text }: { text: string }) {
  const [state, setState] = useState<MarkdownPreviewState>({ status: 'loading' })

  useEffect(() => {
    let cancelled = false
    loadMarkdownCompute()
      .then(compute => compute.parseMarkdown(text) as MarkdownModelRoot)
      .then(model => {
        if (!cancelled) setState({ status: 'ready', model })
      })
      .catch(error => {
        if (cancelled) return
        setState({ status: 'error' })
        reportRuntimeError('渲染 Markdown', error, undefined, {
          scope: { kind: 'sheet', id: 'file-tab:markdown-preview' },
          source: 'file.tab',
        })
      })
    return () => {
      cancelled = true
    }
  }, [text])

  if (state.status === 'error') return <p className="file-tab-hint">Markdown 渲染失败，详情见右下角错误中心</p>
  if (state.status === 'loading') return <p className="file-tab-hint">加载 Markdown…</p>
  return <>{renderModelNodes(state.model.children)}</>
}

export default MarkdownPreview
