// src/renderers/solid-workbench/input/ControlCenter.solid.tsx
import { For, Match, Show, Switch, createEffect, createMemo, createSignal, onCleanup, onMount, type JSX } from 'solid-js'
import { formatTokenCount } from '../../../tokenFormat.ts'
import { CC_WIDGET_IDS, WIDGET_PROPERTY_FIELDS, isExternalSubmitMode, isWidgetVisible, type CcPropertyCommand, type CcWidgetId, type WidgetPropertyField } from '../../../domains/cc/widgetDefinitions.ts'
import type { CcSlot, CcWidgetPlacement } from '../../../ccLayoutState.ts'
import { resolveCcMinHeight, resolveVisibleStatusWidgetCount } from '../../../ccHeightState.ts'
import type { UsageSnapshot } from '../../../domains/workbench/session/sessionSurface.ts'
import { useSolidWorkbench } from '../SolidWorkbenchContext.solid.tsx'
import { SolidInputBar } from './InputBar.solid.tsx'
import { SolidAttachWidget, SolidModeWidget, SolidModelWidget, SolidSendWidget } from './WorkbenchWidgets.solid.tsx'

const STATUS_SLOTS: readonly Exclude<CcSlot, 'input'>[] = ['status-secondary', 'status-primary', 'actions']
const WIDGET_LABELS: Readonly<Record<CcWidgetId, string>> = {
  input: '输入栏', session: '当前会话', workspace: '工作区', activity: '运行状态',
  ekg: '用量条', pct: '百分比', tokens: 'Token数', model: '模型', mode: '权限模式',
  send: '发送按钮', attach: '附件按钮', tasks: '任务',
}

export function SolidControlCenter() {
  const workbench = useSolidWorkbench()
  const appearance = () => workbench.appearanceSnapshot()
  const runtime = () => workbench.runtimeSnapshot()
  const input = () => workbench.input()
  const [selected, setSelected] = createSignal<CcWidgetId>()
  let stopDragging: (() => void) | undefined
  onCleanup(() => stopDragging?.())
  createEffect(() => {
    if (appearance().ccEditMode) return
    setSelected(undefined)
    stopDragging?.()
  })
  onMount(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key !== 'Escape' || !appearance().ccEditMode) return
      if (selected()) setSelected(undefined)
      else {
        stopDragging?.()
        workbench.appearance.dispatch({ type: 'set-cc-edit-mode', enabled: false })
      }
    }
    window.addEventListener('keydown', onKeyDown)
    onCleanup(() => window.removeEventListener('keydown', onKeyDown))
  })
  const readonly = () => input().preview === true || input().replayReadonly === true
  const externalButtonMode = () => isExternalSubmitMode({
    inputMode: appearance().inputMode,
    submitButtonMode: appearance().inputSubmitButtonMode,
  })
  const externalSend = () => externalButtonMode() && !appearance().ccHidden.includes('send')
  const externalAttach = () => externalButtonMode() && !appearance().ccHidden.includes('attach')
  const visibilityContext = () => ({
    hidden: appearance().ccHidden,
    inputMode: appearance().inputMode,
    submitButtonMode: appearance().inputSubmitButtonMode,
    ccStyle: appearance().ccStyle,
    editMode: appearance().ccEditMode,
    presentationProfileId: input().presentationProfileId,
  })
  const visibleIds = createMemo(() => CC_WIDGET_IDS.filter(id => isWidgetVisible(id, visibilityContext())))
  const minHeight = () => resolveCcMinHeight({
    inputMode: appearance().inputMode,
    footerLayout: appearance().footerLayout,
    hintMode: appearance().cliHintMode,
    visibleStatusWidgets: resolveVisibleStatusWidgetCount({
      hiddenIds: appearance().ccHidden,
      inputMode: appearance().inputMode,
      ccStyle: appearance().ccStyle,
      submitButtonMode: appearance().inputSubmitButtonMode,
      presentationProfileId: input().presentationProfileId,
    }),
    cliOverflowMode: appearance().cliOverflowMode,
  })
  const idsForSlot = (slot: CcSlot) => visibleIds()
    .filter(id => appearance().ccLayout.placements[id]?.slot === slot)
    .sort((left, right) => appearance().ccLayout.placements[left].order - appearance().ccLayout.placements[right].order)

  const renderBody = (id: CcWidgetId): JSX.Element | null => {
    switch (id) {
      case 'input':
        return <SolidInputBar externalSend={externalSend()} externalAttach={externalAttach()} disabled={readonly()} predictionProvider={workbench.predictionProvider} />
      case 'session':
        return <span class="cc-info-chip cc-session-chip" title={input().sessionLabel ?? input().sessionId ?? '未选择会话'}>
          <span aria-hidden="true">●</span><span>{input().sessionLabel ?? input().sessionId ?? '未选择会话'}</span>
        </span>
      case 'workspace':
        return <span class="cc-info-chip cc-workspace-chip" title={input().workspacePath ?? input().workspaceLabel ?? '当前会话没有工作目录'}>
          <span aria-hidden="true">▣</span><span>{input().workspaceLabel ?? '无工作目录'}</span>
        </span>
      case 'activity':
        return <span class="cc-info-chip cc-activity-chip" data-running={runtime().generating ? 'true' : 'false'} role="status" aria-live="polite">
          <span aria-hidden="true">{runtime().generating ? '◌' : '●'}</span><span>{runtime().generating ? '生成中' : '就绪'}</span>
        </span>
      case 'ekg':
        return <SolidUsageGauge usage={runtime().document?.session.usage} fallbackTokens={runtime().tokenCount} style={appearance().ccStyle} scale={appearance().ccScale.ekg} />
      case 'pct':
        return <span class="ekg-pct" style={{ 'font-size': `${appearance().ccScale.pct ?? 100}%` }}>{Math.round(contextRatio(runtime().document?.session.usage, runtime().tokenCount) * 100)}%</span>
      case 'tokens': {
        const usage = () => runtime().document?.session.usage
        const limit = () => usage()?.contextLimit
        return <span class="pill-mono" style={{ 'border-left': 'none', padding: '0', 'font-size': `${appearance().ccScale.tokens ?? 100}%` }}>
          {formatTokenCount(usageTokenCount(usage(), runtime().tokenCount))}/{limit() && limit()! > 0 ? formatTokenCount(limit()!) : '—'}
        </span>
      }
      case 'model':
        return <SolidModelWidget />
      case 'mode':
        return <SolidModeWidget />
      case 'send':
        return <SolidSendWidget disabled={readonly()} />
      case 'attach':
        return <SolidAttachWidget disabled={readonly()} />
      case 'tasks': {
        return <Show when={taskLabel(runtime().tasks)}>{label => (
          <button type="button" class="cc-tasks-pill" title="任务列表（点击展开/收起）" onClick={() => window.dispatchEvent(new CustomEvent('pylon:tasks-toggle'))}>{label()}</button>
        )}</Show>
      }
    }
  }

  const renderWidget = (id: CcWidgetId) => {
    const placement = () => appearance().ccLayout.placements[id]
    const body = renderBody(id)
    if (body === null) return null
    return <div
      class={`cc-widget${id === 'input' ? '' : ' cc-natural'}${appearance().ccEditMode ? ' cc-edit' : ''}${appearance().ccHidden.includes(id) ? ' cc-hidden' : ''}${selected() === id ? ' cc-selected' : ''}`}
      data-widget-id={id}
      data-widget-slot={placement().slot}
      style={placementStyle(placement())}
      onPointerDown={event => beginDrag(event, id)}
    >{body}</div>
  }

  const beginDrag = (event: PointerEvent, id: CcWidgetId) => {
    if (!appearance().ccEditMode) return
    event.preventDefault()
    event.stopPropagation()
    setSelected(id)
    stopDragging?.()
    const startX = event.clientX
    const startY = event.clientY
    const pointerId = event.pointerId
    const start = appearance().ccLayout.placements[id]
    const move = (next: PointerEvent) => {
      if (next.pointerId !== pointerId) return
      workbench.appearance.dispatch({
        type: 'update-cc-placement', id,
        placement: {
          offsetX: start.offsetX + next.clientX - startX,
          offsetY: start.offsetY + next.clientY - startY,
        },
      })
    }
    const stop = (next?: PointerEvent) => {
      if (next && next.pointerId !== pointerId) return
      window.removeEventListener('pointermove', move)
      window.removeEventListener('pointerup', stop)
      window.removeEventListener('pointercancel', stop)
      if (stopDragging === stop) stopDragging = undefined
    }
    stopDragging = stop
    window.addEventListener('pointermove', move)
    window.addEventListener('pointerup', stop)
    window.addEventListener('pointercancel', stop)
  }

  const updatePlacement = (id: CcWidgetId, placement: Partial<CcWidgetPlacement>) => {
    workbench.appearance.dispatch({ type: 'update-cc-placement', id, placement })
  }
  const beginHeightDrag = (event: PointerEvent) => {
    event.preventDefault()
    const startY = event.clientY
    const pointerId = event.pointerId
    const startHeight = appearance().ccHeight
    stopDragging?.()
    const move = (next: PointerEvent) => {
      if (next.pointerId !== pointerId) return
      workbench.appearance.dispatch({ type: 'set-cc-height', height: startHeight + startY - next.clientY })
    }
    const stop = (next?: PointerEvent) => {
      if (next && next.pointerId !== pointerId) return
      window.removeEventListener('pointermove', move)
      window.removeEventListener('pointerup', stop)
      window.removeEventListener('pointercancel', stop)
      if (stopDragging === stop) stopDragging = undefined
    }
    stopDragging = stop
    window.addEventListener('pointermove', move)
    window.addEventListener('pointerup', stop)
    window.addEventListener('pointercancel', stop)
  }
  const setProperty = (command: CcPropertyCommand) => workbench.appearance.dispatch(command)
  const propertyFields = (id: CcWidgetId) => WIDGET_PROPERTY_FIELDS[id].filter(field => !field.showIf || field.showIf({
    inputMode: appearance().inputMode,
    ccStyle: appearance().ccStyle,
    barFillFollow: appearance().ccProperties.barFillFollow,
  }))
  const renderPropertyField = (field: WidgetPropertyField, index: number): JSX.Element => {
    if (field.kind === 'section') return <div class="cc-prop-sec" data-field-index={index}>{field.title}</div>
    const value = () => appearance().ccProperties[field.key]
    if (field.kind === 'color') return <div class="cc-prop-field"><label>{field.label}</label><input type="text" class="set-color-input" aria-label={field.label} value={String(value())} onChange={event => setProperty({ type: 'set-cc-property', key: field.key, value: event.currentTarget.value })} /></div>
    if (field.kind === 'number') return <div class="cc-prop-field"><label>{field.label}</label><input type="number" class="set-num" aria-label={field.label} value={Number(value())} min={field.min} max={field.max} step={field.step ?? 1} onInput={event => {
      const next = event.currentTarget.valueAsNumber
      if (Number.isFinite(next)) setProperty({ type: 'set-cc-property', key: field.key, value: Math.max(field.min, Math.min(field.max, next)) })
    }} />{field.suffix && <span>{field.suffix}</span>}</div>
    if (field.kind === 'chips') return <div class="cc-prop-field"><label>{field.label}</label><div class="set-preset-row"><For each={field.options}>{option => (
      <button type="button" class={`set-preset-chip${value() === option.value ? ' active' : ''}`} onClick={() => {
        setProperty({ type: 'set-cc-property', key: field.key, value: option.value })
        if (option.sync) setProperty({ type: 'set-cc-property', key: option.sync.key, value: option.sync.value })
      }}>{option.label}</button>
    )}</For></div></div>
    return <div class="cc-prop-field"><label>{field.label}</label><div class="set-preset-row">
      <button type="button" class={`set-preset-chip${value() !== false ? ' active' : ''}`} onClick={() => setProperty({ type: 'set-cc-property', key: field.key, value: true })}>{field.trueLabel}</button>
      <button type="button" class={`set-preset-chip${value() === false ? ' active' : ''}`} onClick={() => setProperty({ type: 'set-cc-property', key: field.key, value: false })}>{field.falseLabel}</button>
    </div></div>
  }

  const statusSlots = () => <For each={STATUS_SLOTS}>{slot => (
    <div class={`cc-${slot}`} data-cc-slot={slot}>
      <For each={idsForSlot(slot)}>{renderWidget}</For>
    </div>
  )}</For>

  const commandHint = () => appearance().inputMode === 'cli' && appearance().cliHintMode !== 'hidden'
    ? <div class="cc-command-hint" aria-label="输入快捷键提示">
      <span class="cc-command-hint-key">/: 命令</span>
      <span class="cc-hint-secondary"><i>|</i> Shift+Enter: 换行</span>
      {appearance().cliHintMode === 'full' && <span class="cc-hint-tertiary"><i>|</i> Shift+Tab: 模式</span>}
    </div>
    : null

  return <div
    class={`solid-workbench-control-center-slot control-center${appearance().inputMode === 'cli' ? ' cli-mode' : ''}${appearance().ccEditMode ? ' cc-editing' : ''} cc-variant-${appearance().ccVariant}`}
    data-control-center="production"
    style={{
      '--cc-height': `${appearance().ccHeight}px`,
      '--cc-min-height': `${minHeight()}px`,
      '--cc-bg-height': `${appearance().ccBgHeight}px`,
    }}
  >
    <Show when={appearance().ccEditMode}><div
      class="cc-edit-hdr"
      role="separator"
      aria-label="调整中控高度"
      aria-orientation="horizontal"
      aria-valuemin={minHeight()}
      aria-valuemax="400"
      aria-valuenow={appearance().ccHeight}
      tabIndex="0"
      onPointerDown={beginHeightDrag}
      onKeyDown={event => {
        if (event.key !== 'ArrowUp' && event.key !== 'ArrowDown') return
        event.preventDefault()
        workbench.appearance.dispatch({ type: 'set-cc-height', height: appearance().ccHeight + (event.key === 'ArrowUp' ? 4 : -4) })
      }}
    ><div class="cc-edit-hdr-bar" /><span class="cc-edit-hdr-label">{appearance().ccHeight}px</span></div></Show>
    <div class="cc-bg" />
    <div class="cc-body">
      {appearance().footerLayout === 'peri' ? <div class="cc-footer cc-footer-peri">
        <div class="cc-input-slot"><For each={idsForSlot('input')}>{renderWidget}</For></div>
        <div class="cc-footer-status">
          <div class="cc-footer-status-row">{statusSlots()}</div>
          {commandHint()}
        </div>
      </div> : <>
        <div class="cc-input-slot"><For each={idsForSlot('input')}>{renderWidget}</For></div>
        <div class="cc-status-row">{statusSlots()}{commandHint()}</div>
      </>}
    </div>
    <Show when={appearance().ccEditMode && selected()}>{id => (
      <div class="cc-prop-panel" role="dialog" aria-label={`${WIDGET_LABELS[id()]} 属性`}>
        <div class="cc-prop-header"><span>{WIDGET_LABELS[id()]}</span><button type="button" aria-label="关闭属性面板" onClick={() => setSelected(undefined)}>✕</button></div>
        <div class="cc-prop-body">
          <div class="cc-prop-sec">布局</div>
          <div class="cc-prop-field"><label>槽位</label><select class="set-select" aria-label="控件槽位" value={appearance().ccLayout.placements[id()].slot} onChange={event => updatePlacement(id(), { slot: event.currentTarget.value as CcSlot })}>
            <option value="input">输入栏</option><option value="status-primary">状态左</option><option value="status-secondary">状态右</option><option value="actions">操作区</option>
          </select></div>
          <div class="cc-prop-field"><label>顺序</label><input type="number" class="set-num" aria-label="控件顺序" min="0" max="99" step="1" value={appearance().ccLayout.placements[id()].order} onInput={event => {
            const value = event.currentTarget.valueAsNumber
            if (Number.isFinite(value)) updatePlacement(id(), { order: value })
          }} /></div>
          <div class="cc-prop-field"><label>水平微调</label><input type="number" class="set-num" aria-label="水平微调" min="-48" max="48" step="1" value={appearance().ccLayout.placements[id()].offsetX} onInput={event => {
            const value = event.currentTarget.valueAsNumber
            if (Number.isFinite(value)) updatePlacement(id(), { offsetX: value })
          }} /><span>px</span></div>
          <div class="cc-prop-field"><label>垂直微调</label><input type="number" class="set-num" aria-label="垂直微调" min="-16" max="16" step="1" value={appearance().ccLayout.placements[id()].offsetY} onInput={event => {
            const value = event.currentTarget.valueAsNumber
            if (Number.isFinite(value)) updatePlacement(id(), { offsetY: value })
          }} /><span>px</span></div>
          <Show when={id() !== 'input'}><div class="cc-prop-field"><label>缩放</label><input type="number" class="set-num" aria-label="控件缩放" min="50" max="200" step="5" value={appearance().ccScale[id()] ?? 100} onInput={event => {
            const value = event.currentTarget.valueAsNumber
            if (Number.isFinite(value)) workbench.appearance.dispatch({ type: 'set-cc-scale', id: id(), scale: value })
          }} /><span>%</span></div></Show>
          <For each={propertyFields(id())}>{(field, index) => renderPropertyField(field, index())}</For>
        </div>
        <div class="cc-prop-footer"><button type="button" class="ps-btn sm" onClick={() => {
          setSelected(undefined)
          workbench.appearance.dispatch({ type: 'set-cc-edit-mode', enabled: false })
        }}>退出自定义</button></div>
      </div>
    )}</Show>
    <Show when={appearance().ccEditMode}>
      <div class="cc-edit-toolbar" role="toolbar" aria-label="中控控件工具栏">
        <span class="cc-edit-toolbar-label">控件</span>
        <For each={CC_WIDGET_IDS}>{id => {
          const hidden = () => appearance().ccHidden.includes(id)
          return <span class={`cc-edit-toolbar-chip-wrap${selected() === id ? ' active' : ''}${hidden() ? ' dim' : ''}`}>
            <button type="button" class="cc-edit-toolbar-chip" aria-label={`${WIDGET_LABELS[id]} 属性`} onClick={() => setSelected(id)}>{hidden() ? '＋' : '●'} {WIDGET_LABELS[id]}</button>
            <button type="button" class="cc-chip-toggle" aria-label={`${hidden() ? '显示' : '隐藏'} ${WIDGET_LABELS[id]}`} onClick={() => workbench.appearance.dispatch({ type: 'set-cc-hidden', id, hidden: !hidden() })}>{hidden() ? '显示' : '隐藏'}</button>
          </span>
        }}</For>
        <button type="button" class="cc-edit-toolbar-btn" aria-label="重置控件位置" onClick={() => workbench.appearance.dispatch({ type: 'reset-cc-layout' })}>↺ 重置位置</button>
        <button type="button" class="cc-edit-toolbar-btn danger" aria-label="退出中控编辑" onClick={() => {
          setSelected(undefined)
          workbench.appearance.dispatch({ type: 'set-cc-edit-mode', enabled: false })
        }}>退出编辑</button>
      </div>
    </Show>
  </div>
}

function placementStyle(placement: CcWidgetPlacement): JSX.CSSProperties {
  return placement.offsetX === 0 && placement.offsetY === 0
    ? {}
    : { transform: `translate(${placement.offsetX}px, ${placement.offsetY}px)` }
}

function usageTokenCount(usage: UsageSnapshot | undefined, fallback: number): number {
  if (usage?.totalTokens !== undefined) return usage.totalTokens
  const parts = (usage?.inputTokens ?? 0) + (usage?.outputTokens ?? 0)
  return parts > 0 ? parts : Math.max(0, fallback)
}

function contextRatio(usage: UsageSnapshot | undefined, fallback: number): number {
  const explicit = usage?.contextPercent
  if (explicit !== undefined) return clamp01(explicit / 100)
  const limit = usage?.contextLimit ?? 0
  const used = usage?.contextUsed ?? usageTokenCount(usage, fallback)
  return limit > 0 ? clamp01(used / limit) : 0
}

function clamp01(value: number): number {
  return Math.max(0, Math.min(1, Number.isFinite(value) ? value : 0))
}

function SolidUsageGauge(props: { usage?: UsageSnapshot; fallbackTokens: number; style: string; scale?: number }) {
  const ratio = () => contextRatio(props.usage, props.fallbackTokens)
  const percent = () => Math.round(ratio() * 100)
  return <Switch fallback={<svg viewBox="0 0 140 30" class="ekg-svg" preserveAspectRatio="none" aria-label={`上下文 ${percent()}%`} style={{ 'font-size': `${props.scale ?? 100}%` }}>
    <rect x="0" y="12" width={140 * (1 - ratio())} height="6" rx="3" fill="currentColor" opacity="0.3" />
    <rect x={140 * (1 - ratio())} y="12" width={140 * ratio()} height="6" rx="3" fill="var(--ekg-consumed,rgba(128,128,128,0.15))" />
  </svg>}>
    <Match when={props.style === 'numeric'}><span class="ekg-pct" style={{ 'font-size': `${props.scale ?? 100}%` }}>{percent()}%</span></Match>
    <Match when={props.style === 'ring'}><span class="cc-context-ring" role="img" aria-label={`上下文 ${percent()}%`} title={`上下文 ${percent()}%`} style={{ '--context-ring-ratio': ratio(), 'font-size': `${props.scale ?? 100}%` }}>
      <svg viewBox="0 0 24 24" aria-hidden="true"><circle class="cc-context-ring-track" cx="12" cy="12" r="9" pathLength="1" /><circle class="cc-context-ring-value" cx="12" cy="12" r="9" pathLength="1" /></svg>
      <span class="cc-context-ring-label">{percent()}%</span>
    </span></Match>
    <Match when={props.style === 'bar'}><div class="ekg-bar" style={{ '--bar-fill': `${percent()}%`, 'font-size': `${props.scale ?? 100}%` }}><div class="ekg-bar-track" /><div class="ekg-bar-fill" /></div></Match>
  </Switch>
}

function taskLabel(entries: readonly { readonly status: string }[]): string {
  if (entries.length === 0) return ''
  const completed = entries.filter(entry => entry.status === 'completed').length
  const active = entries.filter(entry => entry.status === 'in_progress').length
  return active > 0 ? `任务 ${completed}/${entries.length} · ${active} 进行中` : `任务 ${completed}/${entries.length}`
}

// src/components/ControlCenter.tsx
import { useRef, useState, useCallback, useEffect, useId } from 'react'
import { useStore } from '../store'
import { useRuntimeStore } from '../runtimeStore'
import { useShallow } from 'zustand/react/shallow'
import type { ThemeSettings } from '../store'
import InputBar from './chat/InputBar'
import SendWidget from './chat/SendWidget'
import AttachWidget from './chat/AttachWidget'
import ColorPopover from './ColorPopover'
import { toCssBackgroundImage } from '../backgroundImage'
import { resolveCcMinHeight, resolveVisibleStatusWidgetCount } from '../ccHeightState'
import { CC_WIDGET_REGISTRY as WIDGET_REGISTRY } from './cc/widgetRegistry'
import './ControlCenter.css'
import './chat/StatusBar.css'  // model/mode/send/attach widget 样式

interface Props {
  sessionId: string | null
}

// Widget registry 位于 cc/widgetRegistry.tsx，供中控画布、工具栏和后续 Preview 共用。
export default function ControlCenter({ sessionId }: Props) {
  const ccHeight = useStore(s => s.ccHeight) || 120
  const ccBgHeight = useStore(s => s.ccBgHeight ?? ccHeight)
  const inputMode = useStore(s => s.inputMode)
  const submitButtonMode = useStore(s => s.inputSubmitButtonMode || 'inline')
  const hidden = useStore(s => s.ccHidden || [])
  const ccStyle = useStore(s => s.ccStyle)
  const layout = useStore(s => s.ccLayout)
  const editMode = useStore(s => s.ccEditMode)
  const ccVariant = useStore(s => s.ccVariant) || 'terminal'
  const cliHintMode = useStore(s => s.cliHintMode || 'full')
  const footerLayout = useStore(s => s.footerLayout || 'free')
  const cliOverflowMode = useStore(s => s.cliOverflowMode || 'fixed-scroll')
  const ccBg = useStore(s => s.ccBg) || 'transparent'
  const ccBgImage = useStore(s => s.ccBgImage) || ''
  const setCcEditMode = useStore(s => s.setCcEditMode)
  const setCcHeight = useStore(s => s.setCcHeight)
  const hintId = useId()
  const inputHintId = inputMode === 'cli' && cliHintMode !== 'hidden' ? hintId : undefined

  const inputRef = useRef<{ send: () => void; attachFile: () => void; cancel: () => void }>(null)
  const [selected, setSelected] = useState<string | null>(null)
  // 把 inputRef 转给 SendWidget / AttachWidget
  const renderWidget = (id: string) => {
    const def = WIDGET_REGISTRY.find(w => w.id === id)
    if (!def) return null
    if (!editMode && hidden.includes(id)) return null
    // numeric 由 pct 表达；ring 由用量 widget 表达，避免重复上下文百分比。
    if (!editMode && ccStyle === 'numeric' && id === 'ekg' && !hidden.includes('pct')) return null
    if (!editMode && ccStyle === 'ring' && id === 'pct' && !hidden.includes('ekg')) return null

    // 独立 send/attach widget 仅在"外部按钮模式"下渲染；CLI/内联模式走 InputBar 自带按钮。
    // externalSend/externalAttach 逐按钮决定 InputBar 是否隐藏自带按钮，避免重复或丢失。
    // 可见性判定与 ccHeightState 统一使用 inputMode（Settings 双写保证 inputVariant 与 inputMode 同步）。
    // 编辑模式保持原行为：只要任一外部按钮启用，InputBar 整体让位（画布此时显示全部控件）。
    const externalBtnMode = inputMode !== 'cli' && submitButtonMode === 'external'
    const externalSend = externalBtnMode && !hidden.includes('send')
    const externalAttach = externalBtnMode && !hidden.includes('attach')
    if (!editMode && (id === 'send' || id === 'attach') && !externalBtnMode) return null

    let body: React.ReactNode
    switch (id) {
      case 'input':
        body = <InputBar ref={inputRef} sessionId={sessionId} split={editMode ? (externalSend || externalAttach) : false} externalSend={externalSend} externalAttach={externalAttach} ariaDescribedBy={inputHintId} />
        break
      case 'send':
        body = <SendWidget onClick={() => inputRef.current?.send()} />
        break
      case 'attach':
        body = <AttachWidget onClick={() => inputRef.current?.attachFile()} />
        break
      default:
        body = def.render({ sessionId })
    }

    const placement = layout.placements[id as keyof typeof layout.placements]
    if (!placement) return null
    // 小控件用 naturalSize（宽高由内容决定，盒子紧贴）— 仅 input 占满槽位
    const isNatural = def.naturalSize
    return (
      <EditableWidget
        key={id} id={id} placement={placement} editMode={editMode}
        naturalSize={isNatural}
        isHidden={hidden.includes(id)}
        bodyRef={ccBodyRef}
        selected={selected === id}
        onSelect={() => setSelected(id)}
      >
        {body}
      </EditableWidget>
    )
  }

  const renderSlot = (slot: 'status-primary' | 'status-secondary' | 'actions') => WIDGET_REGISTRY
    .filter(widget => widget.id !== 'input' && layout.placements[widget.id as keyof typeof layout.placements]?.slot === slot)
    .sort((a, b) => (layout.placements[a.id as keyof typeof layout.placements]?.order ?? 0) - (layout.placements[b.id as keyof typeof layout.placements]?.order ?? 0))
    .map(widget => renderWidget(widget.id))

  const ccBodyRef = useRef<HTMLDivElement>(null)
  const visibleStatusWidgets = resolveVisibleStatusWidgetCount({
    hiddenIds: hidden,
    inputMode,
    ccStyle,
  })
  const minHeight = resolveCcMinHeight({
    inputMode,
    footerLayout,
    hintMode: cliHintMode,
    visibleStatusWidgets,
    cliOverflowMode,
  })

  // 整体高度拖拽
  const heightDragCleanupRef = useRef<(() => void) | null>(null)
  useEffect(() => () => { heightDragCleanupRef.current?.() }, [])
  const onHeightDrag = useCallback((e: React.MouseEvent) => {
    e.preventDefault()
    const startY = e.clientY
    const startH = ccHeight
    const onMove = (ev: MouseEvent) => {
      setCcHeight(startH + startY - ev.clientY)
    }
    const onUp = () => {
      heightDragCleanupRef.current = null
      document.removeEventListener('mousemove', onMove)
      document.removeEventListener('mouseup', onUp)
    }
    heightDragCleanupRef.current = onUp
    document.addEventListener('mousemove', onMove)
    document.addEventListener('mouseup', onUp)
  }, [ccHeight, setCcHeight])

  // Escape 退出编辑模式
  useEffect(() => {
    if (!editMode) return
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        if (selected) setSelected(null)
        else setCcEditMode(false)
      }
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [editMode, selected, setCcEditMode])

  return (
    <div className={`control-center ${inputMode === 'cli' ? 'cli-mode' : ''} ${editMode ? 'cc-editing' : ''} cc-variant-${ccVariant}`}
      style={{
        '--cc-height': `${ccHeight}px`,
        '--cc-min-height': `${minHeight}px`,
        '--cc-bg-height': `${ccBgHeight}px`,
        '--cc-bg': ccBg,
        '--cc-bg-image': toCssBackgroundImage(ccBgImage),
      } as React.CSSProperties}>
      {editMode && (
        <div className="cc-edit-hdr" onMouseDown={onHeightDrag}>
          <div className="cc-edit-hdr-bar" />
          <span className="cc-edit-hdr-label">{ccHeight}px</span>
        </div>
      )}
      <div className="cc-bg" />
      <div className="cc-body" ref={ccBodyRef}>
        {footerLayout === 'peri' ? (
          <div className="cc-footer cc-footer-peri">
            <div className="cc-input-slot">{renderWidget('input')}</div>
            <div className="cc-footer-status">
              <div className="cc-footer-status-row">
                <div className="cc-status-secondary">{renderSlot('status-secondary')}</div>
                <div className="cc-status-primary">{renderSlot('status-primary')}</div>
                <div className="cc-actions">{renderSlot('actions')}</div>
              </div>
              {inputMode === 'cli' && cliHintMode !== 'hidden' && (
                <div className="cc-command-hint" id={hintId} aria-label="输入快捷键提示">
                  <span className="cc-command-hint-key">/: 命令</span>
                  <span className="cc-hint-secondary"><i>|</i> Shift+Enter: 换行</span>
                  {cliHintMode === 'full' && <span className="cc-hint-tertiary"><i>|</i> Shift+Tab: 模式</span>}
                </div>
              )}
            </div>
          </div>
        ) : (
          <>
            <div className="cc-input-slot">{renderWidget('input')}</div>
            <div className="cc-status-row">
              <div className="cc-status-secondary">{renderSlot('status-secondary')}</div>
              <div className="cc-status-primary">{renderSlot('status-primary')}</div>
              <div className="cc-actions">{renderSlot('actions')}</div>
              {inputMode === 'cli' && cliHintMode !== 'hidden' && (
                <div className="cc-command-hint" id={hintId} aria-label="输入快捷键提示">
                  <span className="cc-command-hint-key">/: 命令</span>
                  <span className="cc-hint-secondary"><i>|</i> Shift+Enter: 换行</span>
                  {cliHintMode === 'full' && <span className="cc-hint-tertiary"><i>|</i> Shift+Tab: 模式</span>}
                </div>
              )}
            </div>
          </>
        )}
      </div>
      {editMode && selected && <PropertyPanel id={selected} onClose={() => setSelected(null)} onExit={() => { setCcEditMode(false); setSelected(null) }} />}
      {editMode && (
        <WidgetToolbar
          selected={selected}
          onSelect={(id) => setSelected(id)}
        />
      )}
    </div>
  )
}

// ───────────────────────────────────────────────────────────────
// EditableWidget：单一职责，干净指针事件
// ───────────────────────────────────────────────────────────────

function EditableWidget({ id, placement, editMode, isHidden, children, bodyRef, selected, onSelect, naturalSize }: {
  id: string
  placement: { slot: 'input' | 'status-primary' | 'status-secondary' | 'actions'; order: number; offsetX: number; offsetY: number }
  editMode: boolean
  isHidden: boolean
  children: React.ReactNode
  bodyRef: React.RefObject<HTMLDivElement | null>
  selected: boolean
  onSelect: () => void
  // 文字型控件(model/mode/send/attach)用 naturalSize=true — 宽高随内容自适应
  naturalSize?: boolean
}) {
  // 拖拽 / 缩放 — 使用 Pointer Events（统一鼠标+触屏）
  // 直接读 store.getState() 拿最新 pos，避免闭包过期
  const pointerCleanupRef = useRef<(() => void) | null>(null)
  useEffect(() => () => { pointerCleanupRef.current?.() }, [])

  const handleWidgetPointerDown = (e: React.PointerEvent) => {
    if (!editMode) return
    e.stopPropagation()
    e.preventDefault()
    onSelect()
    const body = bodyRef.current; if (!body) return
    const startX = e.clientX, startY = e.clientY
    const currentLayout = useStore.getState().ccLayout
    const start = currentLayout.placements[id as keyof typeof currentLayout.placements] || placement
    const onMove = (ev: PointerEvent) => {
      useStore.getState().updateCcPlacement(id, {
        offsetX: start.offsetX + ev.clientX - startX,
        offsetY: start.offsetY + ev.clientY - startY,
      })
    }
    const onUp = () => {
      pointerCleanupRef.current = null
      window.removeEventListener('pointermove', onMove)
      window.removeEventListener('pointerup', onUp)
    }
    pointerCleanupRef.current = onUp
    window.addEventListener('pointermove', onMove)
    window.addEventListener('pointerup', onUp)
  }

  return (
    <div
      data-widget-id={id}
      className={`cc-widget ${editMode ? 'cc-edit' : ''} ${editMode && isHidden ? 'cc-hidden' : ''} ${selected ? 'cc-selected' : ''} ${naturalSize ? 'cc-natural' : ''}`}
      style={{ transform: `translate(${placement.offsetX}px, ${placement.offsetY}px)` }}
      onPointerDown={editMode ? handleWidgetPointerDown : undefined}
    >
      {children}
    </div>
  )
}

// ───────────────────────────────────────────────────────────────
// WidgetToolbar：编辑模式下浮在画布底部，显示「增删控件」+ 重置
// ───────────────────────────────────────────────────────────────

function WidgetToolbar({ selected, onSelect }: { selected: string | null; onSelect: (id: string | null) => void }) {
  const hidden = useStore(s => s.ccHidden || [])
  const resetCcLayout = useStore(s => s.resetCcLayout)
  const setCcHidden = useStore(s => s.setCcHidden)
  const setCcEditMode = useStore(s => s.setCcEditMode)

  const reset = () => resetCcLayout()

  const toggleHide = (id: string) => {
    setCcHidden(id, !hidden.includes(id))
  }

  return (
    <div className="cc-edit-toolbar">
      <span className="cc-edit-toolbar-label">控件</span>
      {WIDGET_REGISTRY.map(w => {
        const isHidden = hidden.includes(w.id)
        const isSelected = selected === w.id
        return (
          <span key={w.id}
            className={`cc-edit-toolbar-chip-wrap ${isSelected ? 'active' : ''} ${isHidden ? 'dim' : ''}`}>
            <button type="button" className="cc-edit-toolbar-chip"
              onClick={() => onSelect(w.id)}
              title="选中控件（打开属性面板）">
              {isHidden ? '＋' : '●'} {w.label}
            </button>
            <button type="button" className="cc-chip-toggle"
              onClick={() => toggleHide(w.id)}
              title={isHidden ? '已隐藏 — 点击恢复' : '显示中 — 点击隐藏'}>
              {isHidden ? '显示' : '隐藏'}
            </button>
          </span>
        )
      })}
      <button className="cc-edit-toolbar-btn" onClick={reset} title="重置所有控件位置到默认">↺ 重置位置</button>
      <button className="cc-edit-toolbar-btn danger" onClick={() => { setCcEditMode(false); onSelect(null) }}>退出编辑</button>
    </div>
  )
}

// ───────────────────────────────────────────────────────────────
// PropertyPanel — 选中控件的属性编辑面板
// ───────────────────────────────────────────────────────────────

function PropertyPanel({ id, onClose, onExit }: { id: string; onClose: () => void; onExit: () => void }) {
  const placement = useStore(s => s.ccLayout.placements[id as keyof typeof s.ccLayout.placements])
  const u = useStore(s => s.setZoneField)
  const updateCcPlacement = useStore(s => s.updateCcPlacement)
  const setCcScale = useStore(s => s.setCcScale)
  // 只订阅属性面板实际读取的字段：拖拽/生成期间的 live 状态变化不再重渲染面板。
  const theme = useStore(useShallow(s => ({
    ccScale: s.ccScale,
    inputBg: s.inputBg,
    inputTextColor: s.inputTextColor,
    inputFontSize: s.inputFontSize,
    inputMinHeight: s.inputMinHeight,
    inputMode: s.inputMode,
    cliLineWidth: s.cliLineWidth,
    cliLineColor: s.cliLineColor,
    cliLinePadding: s.cliLinePadding,
    ccStyle: s.ccStyle,
    ekgWidth: s.ekgWidth,
    ekgFontSize: s.ekgFontSize,
    ekgGreen: s.ekgGreen,
    ekgYellow: s.ekgYellow,
    ekgRed: s.ekgRed,
    ekgLineWidth: s.ekgLineWidth,
    ekgAmplitudeMax: s.ekgAmplitudeMax,
    ekgSpeedBase: s.ekgSpeedBase,
    ekgSpeedMax: s.ekgSpeedMax,
    barTrackColor: s.barTrackColor,
    barHeight: s.barHeight,
    barFillFollow: s.barFillFollow,
    barFillColor: s.barFillColor,
    modelVariant: s.modelVariant,
    modeVariant: s.modeVariant,
    sendVariant: s.sendVariant,
    attachVariant: s.attachVariant,
  })))
  // liveMode 是运行时状态（runtimeStore 域）
  const liveMode = useRuntimeStore(s => s.liveMode)
  const labels: Record<string, string> = {
    input: '输入栏', ekg: '用量条', pct: '百分比', tokens: 'Token数',
    model: '模型', mode: '权限模式', send: '发送按钮', attach: '附件按钮',
  }

  const up = (k: string, v: any) => u('cc', { [k]: v } as Partial<ThemeSettings>)
  const upOffset = (key: 'offsetX' | 'offsetY', value: number) => updateCcPlacement(id, { [key]: value })

  return (
    <div className="cc-prop-panel">
      <div className="cc-prop-header">
        <span>{labels[id] || id}</span>
        <button onClick={onClose}>✕</button>
      </div>
      <div className="cc-prop-body">
        <div className="cc-prop-sec">布局</div>
        <div className="cc-prop-field"><label>槽位</label>
          <select className="set-select" value={placement?.slot || 'status-primary'} onChange={event => updateCcPlacement(id, { slot: event.target.value as any })}>
            <option value="input">输入栏</option>
            <option value="status-primary">状态左</option>
            <option value="status-secondary">状态右</option>
            <option value="actions">操作区</option>
          </select>
        </div>
        <div className="cc-prop-field"><label>顺序</label><input type="number" value={placement?.order ?? 0} onChange={event => updateCcPlacement(id, { order: +event.target.value })} step={1} className="set-num" min={0} max={99} /></div>
        <div className="cc-prop-field"><label>水平微调</label><input type="number" value={placement?.offsetX ?? 0} onChange={event => upOffset('offsetX', +event.target.value)} step={1} className="set-num" min={-48} max={48} /><span>px</span></div>
        <div className="cc-prop-field"><label>垂直微调</label><input type="number" value={placement?.offsetY ?? 0} onChange={event => upOffset('offsetY', +event.target.value)} step={1} className="set-num" min={-16} max={16} /><span>px</span></div>
        {id !== 'input' && (
          <div className="cc-prop-field"><label>缩放</label>
            <input type="number" value={(theme.ccScale || {})[id] ?? 100}
              onChange={v => setCcScale(id, +v.target.value)}
              step={5} className="set-num" min={50} max={200} /><span>%</span>
          </div>
        )}

        {id === 'input' && <>
          <div className="cc-prop-sec">输入栏设置</div>
          <div className="cc-prop-field"><label>背景色</label><ColorPopover value={theme.inputBg || ''} onChange={v => up('inputBg', v)} /></div>
          <div className="cc-prop-field"><label>文字色</label><ColorPopover value={theme.inputTextColor || ''} onChange={v => up('inputTextColor', v)} /></div>
          <div className="cc-prop-field"><label>字号</label><input type="number" value={theme.inputFontSize} onChange={v => up('inputFontSize', +v.target.value)} step={0.1} className="set-num" min={12} max={22} /></div>
          <div className="cc-prop-field"><label>最小高</label><input type="number" value={theme.inputMinHeight} onChange={v => up('inputMinHeight', +v.target.value)} step={0.1} className="set-num" min={36} max={120} /></div>
          <div className="cc-prop-field"><label>模式</label>
            <div className="set-preset-row">
              {/* 与 Settings 双写保持一致：inputMode 与 inputVariant 必须同步，否则
                  ControlCenter（读 inputMode）与 InputBar（读 inputVariant）会分叉 */}
              <button className={`set-preset-chip ${theme.inputMode === 'default' ? 'active' : ''}`} onClick={() => u('cc', { inputMode: 'default', inputVariant: 'composer' })}>默认</button>
              <button className={`set-preset-chip ${theme.inputMode === 'cli' ? 'active' : ''}`} onClick={() => u('cc', { inputMode: 'cli', inputVariant: 'cli' })}>CLI</button>
            </div>
          </div>
          {theme.inputMode === 'cli' && <>
            <div className="cc-prop-field"><label>线宽</label><input type="number" value={theme.cliLineWidth} onChange={v => up('cliLineWidth', +v.target.value)} step={0.1} className="set-num" min={1} max={6} /></div>
            <div className="cc-prop-field"><label>线色</label><ColorPopover value={theme.cliLineColor || ''} onChange={v => up('cliLineColor', v)} /></div>
            <div className="cc-prop-field"><label>行距</label><input type="number" value={theme.cliLinePadding ?? 6} onChange={v => up('cliLinePadding', +v.target.value)} step={0.1} className="set-num" min={0} max={24} /></div>
          </>}
        </>}

        {id === 'ekg' && <>
          <div className="cc-prop-sec">用量条显示</div>
          <div className="cc-prop-field"><label>仪表类型</label>
            <div className="set-preset-row">
              {(['wave', 'bar', 'ring', 'numeric'] as const).map(s => (
                <button key={s} className={`set-preset-chip ${theme.ccStyle === s ? 'active' : ''}`} onClick={() => up('ccStyle', s)}>
                  {s === 'wave' ? '心电图' : s === 'bar' ? '柱状' : s === 'ring' ? '环形' : '数值'}
                </button>
              ))}
            </div>
          </div>
          <div className="cc-prop-field"><label>宽度</label><input type="number" value={theme.ekgWidth} onChange={v => up('ekgWidth', +v.target.value)} step={0.1} className="set-num" min={80} max={400} /></div>
          <div className="cc-prop-field"><label>字号</label><input type="number" value={theme.ekgFontSize} onChange={v => up('ekgFontSize', +v.target.value)} step={0.1} className="set-num" min={12} max={22} /></div>
          {theme.ccStyle === 'wave' && <>
            <div className="cc-prop-field"><label>绿色</label><ColorPopover value={theme.ekgGreen || ''} onChange={v => up('ekgGreen', v)} /></div>
            <div className="cc-prop-field"><label>黄色</label><ColorPopover value={theme.ekgYellow || ''} onChange={v => up('ekgYellow', v)} /></div>
            <div className="cc-prop-field"><label>红色</label><ColorPopover value={theme.ekgRed || ''} onChange={v => up('ekgRed', v)} /></div>
            <div className="cc-prop-field"><label>线宽</label><input type="number" value={theme.ekgLineWidth} onChange={v => up('ekgLineWidth', +v.target.value)} step={0.1} className="set-num" min={2} max={20} /></div>
            <div className="cc-prop-field"><label>振幅</label><input type="number" value={theme.ekgAmplitudeMax} onChange={v => up('ekgAmplitudeMax', +v.target.value)} step={0.1} className="set-num" min={5} max={30} /></div>
            <div className="cc-prop-field"><label>波速基</label><input type="number" value={theme.ekgSpeedBase} onChange={v => up('ekgSpeedBase', +v.target.value)} step={0.1} className="set-num" min={0} max={3} /></div>
            <div className="cc-prop-field"><label>波速最</label><input type="number" value={theme.ekgSpeedMax} onChange={v => up('ekgSpeedMax', +v.target.value)} step={0.1} className="set-num" min={0} max={5} /></div>
          </>}
          {theme.ccStyle === 'bar' && <>
            <div className="cc-prop-field"><label>外壳背景</label><ColorPopover value={theme.barTrackColor || ''} onChange={v => up('barTrackColor', v)} /></div>
            <div className="cc-prop-field"><label>高度</label><input type="number" value={theme.barHeight ?? 10} onChange={v => up('barHeight', +v.target.value)} step={0.1} className="set-num" min={4} max={40} /></div>
            <div className="cc-prop-field"><label>柱子跟随用量</label>
              <div className="set-preset-row">
                <button className={`set-preset-chip ${theme.barFillFollow !== false ? 'active' : ''}`} onClick={() => up('barFillFollow', true)}>三段色</button>
                <button className={`set-preset-chip ${theme.barFillFollow === false ? 'active' : ''}`} onClick={() => up('barFillFollow', false)}>固定色</button>
              </div>
            </div>
            {theme.barFillFollow === false && (
              <div className="cc-prop-field"><label>柱子颜色</label><ColorPopover value={theme.barFillColor || ''} onChange={v => up('barFillColor', v)} /></div>
            )}
          </>}
        </>}

        {id === 'model' && <>
          <div className="cc-prop-sec">模型控件外观</div>
          <div className="cc-prop-field"><label>外观风格</label>
            <div className="set-preset-row">
              {(['dropdown', 'minimal', 'badge'] as const).map(v => (
                <button key={v} className={`set-preset-chip ${theme.modelVariant === v ? 'active' : ''}`} onClick={() => up('modelVariant', v)}>
                  {v === 'dropdown' ? '下拉' : v === 'minimal' ? '简洁' : '徽章'}
                </button>
              ))}
            </div>
          </div>
        </>}

        {id === 'mode' && <>
          <div className="cc-prop-sec">模式控件外观</div>
          <div className="cc-prop-field"><label>外观风格</label>
            <div className="set-preset-row">
              {(['pill', 'badge', 'minimal'] as const).map(v => (
                <button key={v} className={`set-preset-chip ${theme.modeVariant === v ? 'active' : ''}`} onClick={() => up('modeVariant', v)}>
                  {v === 'pill' ? '胶囊' : v === 'badge' ? '方括号' : '极简'}
                </button>
              ))}
            </div>
          </div>
          <div className="cc-prop-field"><label>当前</label><span style={{ fontSize: 13, color: liveMode === 'bypass' ? '#FF6B80' : liveMode === 'auto' ? '#FFC107' : liveMode === 'edit' ? '#A2A9E4' : '#999' }}>{liveMode || 'default'}</span></div>
        </>}

        {id === 'send' && <>
          <div className="cc-prop-sec">发送按钮外观</div>
          <div className="cc-prop-field"><label>外观风格</label>
            <div className="set-preset-row">
              {(['icon', 'square', 'minimal'] as const).map(v => (
                <button key={v} className={`set-preset-chip ${theme.sendVariant === v ? 'active' : ''}`} onClick={() => up('sendVariant', v)}>
                  {v === 'icon' ? '圆形' : v === 'square' ? '方形' : '极简'}
                </button>
              ))}
            </div>
          </div>
        </>}

        {id === 'attach' && <>
          <div className="cc-prop-sec">附件按钮外观</div>
          <div className="cc-prop-field"><label>外观风格</label>
            <div className="set-preset-row">
              {(['icon', 'square', 'minimal'] as const).map(v => (
                <button key={v} className={`set-preset-chip ${theme.attachVariant === v ? 'active' : ''}`} onClick={() => up('attachVariant', v)}>
                  {v === 'icon' ? '圆形' : v === 'square' ? '方形' : '极简'}
                </button>
              ))}
            </div>
          </div>
        </>}
      </div>
      <div className="cc-prop-footer">
        <button className="ps-btn sm" onClick={onExit}>退出自定义</button>
      </div>
    </div>
  )
}
