// src/components/settings/AgentRuntimePanel.tsx
import { useState } from 'react'
import { invoke } from '@tauri-apps/api/core'
import { IS_TAURI } from '../../infrastructure/tauri/env'
import {
  createAgentClient,
  type AgentCreateConfig,
  type AgentsConfigDocument,
} from '../../infrastructure/acp/agentClient'
import { reportRuntimeError } from '../../runtimeError'
import { useIdentityStore, type AgentEntry } from '../../identityStore'
import { useRuntimeStore } from '../../runtimeStore'
import { selectAgentStatus, statusLabel } from './agentTypes'
import { getPluginServiceRegistry } from '../../plugin-runtime/runtimeServices.ts'
import { selectAcpRuntimeDetectorIds, type AgentDetectionDiagnostic, type AgentRuntimeCandidate, type AgentRuntimeDetectorMetadata } from '../../domains/agent/agentDetector.ts'
import {
  candidateImportMode,
  candidateValidationDetails,
  type AgentCandidateValidationState,
} from '../../domains/agent/candidateValidation.ts'
import ArgumentListEditor from './ArgumentListEditor.tsx'
import { describeInvocation, validateInvocation } from '../../domains/agent/invocationDraft.ts'

interface Draft {
  name: string
  exe: string
  provider: string
  args: string[]
  effectiveSuffix: string[]
  argsKnown: boolean
}

interface CandidateDraft { id: string; name: string; executable: string; args: string[]; provider: string }

function emptyDraft(agent?: AgentEntry): Draft {
  const args = agent?.args ? [...agent.args] : []
  const effectiveArgs = agent?.effectiveArgs ?? args
  const hasMatchingPrefix = args.every((argument, index) => effectiveArgs[index] === argument)
  return {
    name: agent?.name ?? '',
    exe: agent?.exe ?? '',
    provider: agent?.provider ?? '',
    args,
    effectiveSuffix: hasMatchingPrefix ? effectiveArgs.slice(args.length) : [],
    argsKnown: agent?.args !== undefined,
  }
}

function agentConfig(name: string, exe: string, args: readonly string[], isFirst: boolean): AgentCreateConfig {
  return {
    name: name.trim(),
    provider: 'custom',
    transport: 'subprocess',
    exe: exe.trim(),
    args: [...args],
    default: isFirst,
  }
}

function candidateDraft(candidate: AgentRuntimeCandidate): CandidateDraft {
  return { id: candidate.suggestedAgentId, name: candidate.name, executable: candidate.executable, args: [...candidate.args], provider: candidate.provider }
}

function detectedAgentConfig(draft: CandidateDraft, isFirst: boolean): AgentCreateConfig {
  return {
    name: draft.name.trim(),
    provider: draft.provider.trim(),
    transport: 'subprocess',
    exe: draft.executable.trim(),
    args: [...draft.args],
    default: isFirst,
  }
}

function agentsDocument(id: string, config: AgentCreateConfig): AgentsConfigDocument {
  return { agents: { [id]: config } }
}

function wireErrorCode(error: unknown): string | undefined {
  if (error && typeof error === 'object') return (error as { code?: unknown }).code as string | undefined
  return undefined
}

function invocationError(executable: string, args: string[]): string | null {
  const error = validateInvocation({ executable, args }).issues.find(issue => issue.severity === 'error')
  return error?.message ?? null
}

function InvocationPreview({ executable, args, effectiveArgs = args }: {
  executable: string
  args: string[]
  effectiveArgs?: string[]
}) {
  const invocation = describeInvocation({ executable, args }, effectiveArgs)
  return (
    <div className="agent-invocation-preview">
      <div className="set-hint">实际启动：<code>{invocation.display}</code></div>
      {invocation.validation.issues.map(issue => (
        <div className="set-hint" role={issue.severity === 'error' ? 'alert' : 'note'} key={`${issue.code}:${issue.argumentIndex ?? 'exe'}`}>
          {issue.severity === 'error' ? '错误' : '提示'}：{issue.message}
        </div>
      ))}
    </div>
  )
}

function candidateProtocolLabel(validation: AgentCandidateValidationState | undefined): string {
  if (validation?.status === 'testing') return '验证中'
  if (validation?.status === 'ok') return '可用'
  if (validation?.status === 'failed') return '失败'
  return '未验证'
}

function activationLabel(state: AgentEntry['configActivationState']): string {
  return state === 'activated' ? '已生效' : state === 'pendingRestart' ? '待重启生效' : '已存储'
}

/** 按 provider 给 exe/命令路径填写引导（任务：说明 hermes/peri 分别填什么路径）。 */
function pathHintForProvider(provider: string | null | undefined): string {
  switch ((provider ?? '').trim().toLowerCase()) {
    case 'hermes':
      return 'Hermes 填法：exe 填 hermes 命令名（在 PATH 中）或 Hermes 启动脚本绝对路径；若需固定 provider/密钥，再补 hermes_profile（profile 名或目录）。'
    case 'peri':
      return 'Peri 填法：exe 填 peri.exe 的绝对路径，例如 F:\\A-I\\Agent\\Peri\\target\\release\\peri.exe（PATH 内也可只填 peri）。'
    default:
      return 'exe 填法：Agent 可执行文件绝对路径；PATH 内的命令（claude、hermes、peri 等）也可只填命令名。'
  }
}

/**
 * 施工文档 §4.1：Agent 运行时配置面板。
 * 复用既有 Settings agent section 边界；结构化操作（exe/name/provider/default/新建/测试）
 * 全部走 typed client，不重建整块 YAML。
 */
export default function AgentRuntimePanel() {
  const [agentClient] = useState(() => createAgentClient({
    invoke: (cmd, args) => invoke(cmd, args as Record<string, unknown> | undefined),
  }))
  const agents = useIdentityStore(s => s.agents)
  const activeAgent = useIdentityStore(s => s.activeAgent)
  const agentStatuses = useRuntimeStore(s => s.agentStatuses)
  const [editingId, setEditingId] = useState<string | null>(null)
  const [draft, setDraft] = useState<Draft>(emptyDraft())
  const [savingId, setSavingId] = useState<string | null>(null)
  const [testingId, setTestingId] = useState<string | null>(null)
  const [testResult, setTestResult] = useState<Record<string, string>>({})
  const [showCreate, setShowCreate] = useState(false)
  const [createDraft, setCreateDraft] = useState({ id: '', name: '', exe: '', args: ['acp'] })
  const [feedback, setFeedback] = useState<string | null>(null)
  const [configConflict, setConfigConflict] = useState(false)
  const [toast, setToast] = useState<string | null>(null)
  // 轻量操作提示：保存/新建/导入成功等「需要弹出」的反馈走 toast，自动消失；
  // 压缩/校验等详情性提示仍走 setFeedback 内联。
  const notify = (message: string) => {
    setToast(message)
    window.setTimeout(() => setToast(null), 2500)
  }
  const [candidates, setCandidates] = useState<AgentRuntimeCandidate[]>([])
  const [detectionDiagnostics, setDetectionDiagnostics] = useState<AgentDetectionDiagnostic[]>([])
  const [detectionElapsedMs, setDetectionElapsedMs] = useState(0)
  const [detectionTruncated, setDetectionTruncated] = useState(false)
  const [detecting, setDetecting] = useState(false)
  const [candidateValidation, setCandidateValidation] = useState<Record<string, AgentCandidateValidationState>>({})
  const [candidateDrafts, setCandidateDrafts] = useState<Record<string, CandidateDraft>>({})

  const reportConfigMutationError = (operation: string, error: unknown, agentId?: string) => {
    const detail = reportRuntimeError(operation, error, agentId)
    if (wireErrorCode(error) === 'config_revision_conflict') {
      setConfigConflict(true)
      setFeedback('配置已被其他进程修改；你的草稿仍保留。请重新载入配置后再提交。')
      return detail
    }
    setFeedback(`${operation}失败：${detail.message}`)
    return detail
  }

  const reloadConfigSnapshot = async () => {
    try {
      await agentClient.agentConfigSnapshot()
      await refreshAgents()
      setConfigConflict(false)
      setFeedback('配置已重新载入；未提交草稿仍保留。')
    } catch (error) {
      const detail = reportRuntimeError('重新载入 Agent 配置', error)
      setFeedback(`重新载入失败：${detail.message}`)
    }
  }

  const detectRuntimes = async () => {
    if (detecting) return
    setDetecting(true)
    try {
      const detectors = getPluginServiceRegistry().list<AgentRuntimeDetectorMetadata>('agent-detector')
      const report = await agentClient.detectAgentRuntimes(selectAcpRuntimeDetectorIds(detectors))
      setCandidates(report.candidates)
      setDetectionDiagnostics(report.diagnostics)
      setDetectionElapsedMs(report.elapsedMs)
      setDetectionTruncated(report.truncated)
    } catch (error) {
      reportRuntimeError('探测本机 Agent', error)
      setFeedback(`探测失败：${error instanceof Error ? error.message : String(error)}`)
    } finally { setDetecting(false) }
  }

  const validateCandidate = async (candidate: AgentRuntimeCandidate) => {
    const draft = candidateDrafts[candidate.candidateId] ?? candidateDraft(candidate)
    const invalid = invocationError(draft.executable, draft.args)
    if (invalid) { setFeedback(invalid); return }
    setFeedback(null)
    setCandidateValidation(current => ({ ...current, [candidate.candidateId]: { status: 'testing' } }))
    const result = await agentClient.testAgentCandidate(draft.id, {
      name: draft.name, provider: draft.provider, transport: 'subprocess', exe: draft.executable, args: [...draft.args],
    }).catch(error => {
      const detail = reportRuntimeError('验证 Agent 候选', error)
      return {
        ok: false,
        agentId: draft.id,
        durationMs: 0,
        error: { code: detail.code ?? 'agent_validation_transport_failed', message: detail.message, action: 'open-runtime-log', stage: 'unknown' as const, exitCode: null, stderr: null },
      }
    })
    setCandidateValidation(current => ({ ...current, [candidate.candidateId]: { status: result.ok ? 'ok' : 'failed', result } }))
  }

  const importCandidate = async (candidate: AgentRuntimeCandidate) => {
    const importMode = candidateImportMode(candidate, candidateValidation[candidate.candidateId])
    if (importMode === 'blocked') {
      setFeedback(candidateValidation[candidate.candidateId]?.status === 'failed'
        ? '该候选置信度不足，必须通过 ACP 验证后才能导入'
        : '请先验证候选，再执行导入')
      return
    }
    const draft = candidateDrafts[candidate.candidateId] ?? candidateDraft(candidate)
    const base = draft.id.trim()
    if (!base || !draft.name.trim() || !draft.executable.trim()) { setFeedback('候选 id / name / exe 不能为空'); return }
    const invalid = invocationError(draft.executable, draft.args)
    if (invalid) { setFeedback(invalid); return }
    let id = base; let suffix = 2
    while (agents.some(agent => agent.id === id)) id = `${base}-${suffix++}`
    const config = detectedAgentConfig(draft, agents.length === 0)
    try {
      try {
        await agentClient.createAgent(id, config)
      } catch (error) {
        if (wireErrorCode(error) !== 'config_read_only') throw error
        await agentClient.initializeAgentsConfig(id, agentsDocument(id, config))
      }
      await refreshAgents()
      setConfigConflict(false)
      setFeedback(null)
      notify(`已导入 ${draft.name}（${id}）${importMode === 'unverified' ? '；状态：未验证' : ''}`)
      await detectRuntimes()
    } catch (error) {
      reportConfigMutationError('导入 Agent 候选', error, id)
    }
  }

  const updateCandidateDraft = (candidate: AgentRuntimeCandidate, patch: Partial<CandidateDraft>) => {
    setCandidateDrafts(current => ({ ...current, [candidate.candidateId]: { ...(current[candidate.candidateId] ?? candidateDraft(candidate)), ...patch } }))
    setCandidateValidation(current => {
      const next = { ...current }
      delete next[candidate.candidateId]
      return next
    })
  }

  const refreshAgents = async () => {
    const list = await agentClient.listAgents()
    useIdentityStore.getState().setAgents(list)
  }

  const startEdit = (agent: AgentEntry) => {
    setEditingId(agent.id)
    setDraft(emptyDraft(agent))
    setFeedback(null)
  }

  const pickExecutable = async (): Promise<string | null> => {
    if (IS_TAURI) {
      const { open } = await import('@tauri-apps/plugin-dialog')
      const selected = await open({
        multiple: false,
        directory: false,
        filters: [{ name: '可执行文件', extensions: ['exe', 'cmd', 'bat'] }],
      })
      return typeof selected === 'string' ? selected : null
    }
    // 浏览器 mock：可控替代行为（测试注入 prompt 返回值）。
    return window.prompt('输入可执行文件路径（exe/cmd/bat）')
  }

  const saveEdit = async (agentId: string) => {
    if (savingId) return
    const invalid = invocationError(draft.exe, draft.args)
    if (invalid) { setFeedback(invalid); return }
    setSavingId(agentId)
    setFeedback(null)
    try {
      await agentClient.ensureConfigRevision()
      await agentClient.updateAgentFieldPatch(agentId, {
        name: draft.name,
        exe: draft.exe,
        provider: draft.provider.trim() || null,
        ...(draft.argsKnown ? { args: [...draft.args] } : {}),
      })
      await refreshAgents()
      setEditingId(null)
      setConfigConflict(false)
      setFeedback(null)
      notify(`已保存 ${agentId}`)
    } catch (error) {
      reportConfigMutationError('保存 Agent 字段', error, agentId)
      notify(`保存失败：${agentId}`)
    } finally {
      setSavingId(null)
    }
  }

  const setDefault = async (agentId: string) => {
    if (savingId) return
    setSavingId(agentId)
    setFeedback(null)
    try {
      await agentClient.ensureConfigRevision()
      try {
        await agentClient.updateAgentFieldPatch(agentId, { default: true })
      } catch (error) {
        if (wireErrorCode(error) !== 'config_read_only') throw error
        await agentClient.initializeAgentFieldPatch(agentId, { default: true })
      }
      await refreshAgents()
      setConfigConflict(false)
      setFeedback(null)
      notify(`已将 ${agentId} 设为默认`)
    } catch (error) {
      reportConfigMutationError('设置默认 Agent', error, agentId)
    } finally {
      setSavingId(null)
    }
  }

  const testConnection = async (agentId: string) => {
    if (testingId) return
    setTestingId(agentId)
    setTestResult(prev => ({ ...prev, [agentId]: '测试中…' }))
    try {
      const result = await agentClient.testAgentConnection(agentId)
      setTestResult(prev => ({
        ...prev,
        [agentId]: result.ok
          ? `连接成功（${result.durationMs}ms）`
          : `连接失败：${result.error?.message ?? '未知错误'}`,
      }))
    } catch (error) {
      const detail = reportRuntimeError('测试 Agent 连接', error, agentId)
      setTestResult(prev => ({ ...prev, [agentId]: detail.message }))
    } finally {
      setTestingId(null)
    }
  }

  const restartRuntime = async (agentId: string) => {
    if (savingId) return
    setSavingId(agentId)
    setFeedback(null)
    try {
      await agentClient.restartAgentRuntime(agentId)
      await refreshAgents()
      notify(`已重启 ${agentId} 并应用配置`)
    } catch (error) {
      reportConfigMutationError('重启 Agent runtime', error, agentId)
    } finally {
      setSavingId(null)
    }
  }

  const createAgent = async () => {
    const id = createDraft.id.trim()
    if (!id || !createDraft.name.trim() || !createDraft.exe.trim()) {
      setFeedback('新建 Agent 必须填写 id / name / exe')
      return
    }
    const invalid = invocationError(createDraft.exe, createDraft.args)
    if (invalid) { setFeedback(invalid); return }
    setFeedback(null)
    const config = agentConfig(createDraft.name, createDraft.exe, createDraft.args, agents.length === 0)
    try {
      await agentClient.ensureConfigRevision()
      await agentClient.createAgent(id, config)
      await refreshAgents()
      setShowCreate(false)
      setConfigConflict(false)
      setCreateDraft({ id: '', name: '', exe: '', args: ['acp'] })
      setFeedback(null)
      notify(`已新建 Agent ${id}`)
    } catch (error) {
      // 施工文档 §4.6：embedded source 首次配置——create 撞 config_read_only 时，
      // 自动改为在 exe 旁初始化外部 agents.yaml（同一最小配置）。
      if (wireErrorCode(error) === 'config_read_only') {
        try {
          await agentClient.initializeAgentsConfig(id, agentsDocument(id, config))
          await refreshAgents()
          setShowCreate(false)
          setCreateDraft({ id: '', name: '', exe: '', args: ['acp'] })
          setFeedback(`已初始化外部配置并新建 Agent ${id}`)
        } catch (initError) {
          reportConfigMutationError('初始化 Agent 配置', initError, id)
        }
        return
      }
      reportConfigMutationError('新建 Agent', error, id)
    }
  }

  return (
    <div className="agent-runtime-panel">
      {toast && (
        <div className="agent-runtime-toast" role="status" aria-live="polite">{toast}</div>
      )}
      {feedback && <div className="set-hint" role="status">{feedback}</div>}
      {configConflict && (
        <button type="button" className="set-btn" onClick={() => void reloadConfigSnapshot()}>
          重新载入配置
        </button>
      )}

      {agents.length === 0 && (
        <div className="set-hint" role="status">
          当前没有 Agent 配置。点击“新建 Agent”创建首个外部配置。
        </div>
      )}

      {agents.map(agent => {
        const status = selectAgentStatus(agent.id, activeAgent, agentStatuses)
        const isEditing = editingId === agent.id
        return (
          <div className="agent-runtime-card" key={agent.id}>
            <div className="set-hint" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <strong>{agent.name}</strong>
              <span>{agent.id === activeAgent ? '当前' : ''}{agent.default ? ' · 默认' : ''}</span>
            </div>
            <div className="set-hint">id：{agent.id} · provider：{agent.provider ?? '—'} · transport：{agent.transport ?? 'subprocess'}</div>
            <div className="set-hint">状态：{statusLabel(status.status)} · 配置：{activationLabel(agent.configActivationState)} · exe：{isEditing ? '' : (agent.exe ?? '—')}</div>

            {isEditing && (
              <div className="agent-runtime-edit">
                <input className="set-input" value={draft.name} onChange={event => setDraft({ ...draft, name: event.target.value })} placeholder="name" aria-label="Agent name" />
                <input className="set-input" value={draft.exe} onChange={event => setDraft({ ...draft, exe: event.target.value })} placeholder="exe 绝对路径或命令名" aria-label="Agent exe" />
                <div className="set-hint" role="note">{pathHintForProvider(draft.provider || agent.provider)}</div>
                <div className="set-preset-row">
                  <button className="ps-btn sm" type="button" onClick={() => pickExecutable().then(path => { if (path) setDraft(d => ({ ...d, exe: path })) })}>选择可执行文件</button>
                  <input className="set-input" value={draft.provider} onChange={event => setDraft({ ...draft, provider: event.target.value })} placeholder="provider（可空）" aria-label="Agent provider" />
                </div>
                <ArgumentListEditor args={draft.args} label={agent.id} onChange={args => setDraft({ ...draft, args, argsKnown: true })} />
                <InvocationPreview executable={draft.exe} args={draft.args} effectiveArgs={[...draft.args, ...draft.effectiveSuffix]} />
              </div>
            )}

            {testResult[agent.id] && <div className="set-hint" role="status">{testResult[agent.id]}</div>}

            <div className="set-preset-row">
              {isEditing ? (
                <>
                  <button className="ps-btn sm primary" type="button" disabled={savingId !== null} onClick={() => saveEdit(agent.id)}>{savingId === agent.id ? '保存中…' : '保存'}</button>
                  <button className="ps-btn sm" type="button" disabled={savingId !== null} onClick={() => setEditingId(null)}>取消</button>
                </>
              ) : (
                <button className="ps-btn sm" type="button" disabled={savingId !== null} onClick={() => startEdit(agent)}>编辑</button>
              )}
              <button className="ps-btn sm" type="button" disabled={savingId !== null || agent.default === true} onClick={() => setDefault(agent.id)}>设为默认</button>
              <button className="ps-btn sm" type="button" disabled={testingId !== null} onClick={() => testConnection(agent.id)}>{testingId === agent.id ? '测试中…' : '测试连接'}</button>
              {agent.configActivationState === 'pendingRestart' && (
                <button className="ps-btn sm primary" type="button" disabled={savingId !== null} onClick={() => void restartRuntime(agent.id)}>
                  {savingId === agent.id ? '正在重启…' : '立即重启应用此配置'}
                </button>
              )}
            </div>
          </div>
        )
      })}

      <section className="agent-runtime-discovery" aria-label="发现的运行时">
        <div className="set-preset-row" style={{ marginTop: 12 }}>
          <strong>发现的运行时（{candidates.length}）</strong>
          <button className="ps-btn sm" type="button" disabled={detecting} onClick={() => void detectRuntimes()}>{detecting ? '探测中…' : '重新探测'}</button>
        </div>
        {(detectionElapsedMs > 0 || detectionTruncated) && (
          <div className="set-hint">探测耗时：{detectionElapsedMs}ms{detectionTruncated ? ' · 结果已截断' : ''}</div>
        )}
        {detectionDiagnostics.map((diagnostic, index) => (
          <div className="set-hint" role="status" key={`${diagnostic.code}:${diagnostic.detectorId ?? 'all'}:${index}`}>
            {diagnostic.code}（{diagnostic.stage}）：{diagnostic.message}
          </div>
        ))}
        {candidates.map(candidate => {
          const discoveredDraft = candidateDrafts[candidate.candidateId] ?? candidateDraft(candidate)
          const validation = candidateValidation[candidate.candidateId]
          const importMode = candidateImportMode(candidate, validation)
          const validationDetails = validation ? candidateValidationDetails(validation) : null
          return <div className="agent-runtime-card" key={candidate.candidateId}>
          <div className="set-hint"><strong>{candidate.name}</strong> · 身份可信度：{candidate.identityConfidence} · ACP：{candidateProtocolLabel(validation)} · {candidate.alreadyImportedAgentId ? `已导入为 ${candidate.alreadyImportedAgentId}` : '尚未导入'}</div>
          <div className="agent-runtime-edit">
            <input className="set-input" value={discoveredDraft.id} onChange={event => updateCandidateDraft(candidate, { id: event.target.value })} aria-label={`${candidate.name} Agent id`} />
            <input className="set-input" value={discoveredDraft.name} onChange={event => updateCandidateDraft(candidate, { name: event.target.value })} aria-label={`${candidate.name} Agent name`} />
            <input className="set-input" value={discoveredDraft.executable} onChange={event => updateCandidateDraft(candidate, { executable: event.target.value })} aria-label={`${candidate.name} executable`} />
            <ArgumentListEditor args={discoveredDraft.args} label={candidate.name} onChange={args => updateCandidateDraft(candidate, { args })} />
            <input className="set-input" value={discoveredDraft.provider} onChange={event => updateCandidateDraft(candidate, { provider: event.target.value })} aria-label={`${candidate.name} provider`} />
            <InvocationPreview executable={discoveredDraft.executable} args={discoveredDraft.args} />
          </div>
          {candidate.evidence.map((evidence, index) => <div className="set-hint" key={`${evidence.kind}:${index}`}>{evidence.kind}：{evidence.detail}</div>)}
          {candidate.warnings.map(warning => <div className="set-hint" role="alert" key={warning}>{warning}</div>)}
          <div className="set-preset-row">
            <button className="ps-btn sm" type="button" disabled={validation?.status === 'testing'} onClick={() => void validateCandidate(candidate)}>{validation?.status === 'testing' ? '验证中…' : '验证'}</button>
            <button className="ps-btn sm primary" type="button" disabled={candidate.alreadyImportedAgentId !== undefined || importMode === 'blocked'} onClick={() => void importCandidate(candidate)}>{importMode === 'unverified' ? '导入（未验证）' : '导入'}</button>
            {validation?.status === 'testing' && <span className="set-hint">ACP 验证中，最长 15 秒</span>}
          </div>
          {validationDetails && <div className={`agent-candidate-validation ${validation?.status === 'failed' ? 'failed' : 'ok'}`} role="status">
            <strong>{validationDetails.headline}</strong>
            <span>耗时：{validationDetails.duration} · 阶段：{validationDetails.stage} · 退出码：{validationDetails.exitCode}</span>
            {validationDetails.message && <span>{validationDetails.message}</span>}
            {validation?.status === 'failed' && <pre>stderr：{validationDetails.stderr}</pre>}
            {importMode === 'unverified' && <span>高置信候选可继续导入，导入后标记为未验证。</span>}
            {validation?.status === 'failed' && importMode === 'blocked' && <span>当前置信度必须通过验证后才能导入。</span>}
          </div>}
        </div>})}
      </section>

      <div className="set-preset-row" style={{ marginTop: 12 }}>
        <button className="ps-btn sm" type="button" onClick={() => setShowCreate(value => !value)}>
          {showCreate ? '收起新建' : '新建 Agent'}
        </button>
      </div>

      {showCreate && (
        <div className="agent-runtime-create" aria-label="新建 Agent 配置">
          <input className="set-input" value={createDraft.id} onChange={event => setCreateDraft({ ...createDraft, id: event.target.value })} placeholder="id（字母开头，可含 . _ -）" aria-label="新建 Agent id" />
          <input className="set-input" value={createDraft.name} onChange={event => setCreateDraft({ ...createDraft, name: event.target.value })} placeholder="name" aria-label="新建 Agent name" />
          <input className="set-input" value={createDraft.exe} onChange={event => setCreateDraft({ ...createDraft, exe: event.target.value })} placeholder="exe 绝对路径或命令名" aria-label="新建 Agent exe" />
          <ArgumentListEditor args={createDraft.args} label="新建 Agent" onChange={args => setCreateDraft({ ...createDraft, args })} />
          <InvocationPreview executable={createDraft.exe} args={createDraft.args} />
          <div className="set-hint" role="note">{pathHintForProvider(null)}</div>
          <button className="ps-btn sm primary" type="button" disabled={savingId !== null} onClick={createAgent}>创建</button>
        </div>
      )}
    </div>
  )
}

// src/components/settings/AgentRuntimePanel.solid.tsx
/** @jsxImportSource solid-js */
import { createEffect, createSignal, For, Show } from 'solid-js'
import { appClients } from '../../app/appClients.ts'
import { errorCode as wireErrorCode } from '../../infrastructure/tauri/errorPayload.ts'
import { reportRuntimeError, resolveRuntimeErrors } from '../../app/runtimeError.ts'
import { useIdentityStore, type AgentEntry } from '../../domains/identity/identityStore'
import { useRuntimeStore } from '../../domains/runtime/runtimeStore'
import { selectAgentStatus } from '../../contracts/agentTypes'
import { validateInvocation } from '../../domains/agent/invocationDraft.ts'
import { builtinAgentCatalog } from '../../domains/agent/agentCatalog.ts'
import {
  agentDraftFingerprint,
  agentDraftReducer,
  canSaveAgentDraft,
  initialAgentDraftState,
  type AgentDraftState,
} from '../../domains/agent/agentDraftMachine.ts'
import {
  assertCustomProfileFieldsAllowed,
  validateCustomProfile,
} from '../../domains/agent/customProfileRules.ts'
import { createZustandSignal } from '../../infrastructure/state/solidStoreBridge.ts'
import { createAgentDetection } from './useAgentDetection.solid.ts'
import { createAgentPanelFeedback } from './useAgentPanelFeedback.solid.ts'
import { createAgentCandidateProvisioning } from './useAgentCandidateProvisioning.solid.ts'
import AgentRuntimeCard from './AgentRuntimeCard.solid.tsx'
import AgentCandidateList from './AgentCandidateList.solid.tsx'
import AgentCreateForm, { type AgentCreateDraftInput } from './AgentCreateForm.solid.tsx'
import { emptyDraft, agentConfig, agentsDocument, type Draft } from './agentRuntimePanelDrafts'

function invocationError(executable: string, args: string[]): string | null {
  const error = validateInvocation({ executable, args }).issues.find(issue => issue.severity === 'error')
  return error?.message ?? null
}

interface AgentRuntimePanelProps {
  initialAgentId?: string
}

/**
 * 施工文档 §4.1：Agent 运行时配置面板。
 * 复用既有 Settings agent section 边界；结构化操作（exe/name/provider/default/新建/测试）
 * 全部走 typed client，不重建整块 YAML。
 *
 * A-V4 拆分后本组件只保留：编辑流状态机（草稿→验证→保存，跨卡单飞）与卡级事务、
 * 新建事务、装配。探测流在 createAgentDetection；候选验证/导入在
 * createAgentCandidateProvisioning；反馈双通道（feedback/toast/冲突横幅）在
 * createAgentPanelFeedback；呈现分别在 AgentRuntimeCard / AgentCandidateList /
 * AgentCreateForm。
 *
 * #515 W1：Solid 实体。
 * store 消费经 createZustandSignal（selector 只读 store）；副作用用
 * createEffect/onCleanup 承担，跨渲染可变量用组件体局部 let。
 */
export default function AgentRuntimePanel(props: AgentRuntimePanelProps) {
  const agentClient = appClients.agent()
  const agents = createZustandSignal(useIdentityStore, s => s.agents)
  const activeAgent = createZustandSignal(useIdentityStore, s => s.activeAgent)
  const agentStatuses = createZustandSignal(useRuntimeStore, s => s.agentStatuses)
  const [editingId, setEditingId] = createSignal<string | null>(null)
  const [draft, setDraft] = createSignal<Draft>(emptyDraft())
  const [savingId, setSavingId] = createSignal<string | null>(null)
  const [testingId, setTestingId] = createSignal<string | null>(null)
  const [testResult, setTestResult] = createSignal<Record<string, string>>({})
  // B1：编辑流的草稿→验证→保存生命周期收拢为显式状态机（旧 verifiedDrafts
  // 散落三处 state 的不变量在此由 reducer + 测试锁定）。Solid 无 useState 惰性初始化，
  // 工厂就地求值。
  const [draftMachine, setDraftMachine] = createSignal<AgentDraftState>(initialAgentDraftState())
  // B1：最近一次草稿验证返回的启动计划（与真实 spawn 同源；env 已在后端掩码）。
  const [draftLaunchPlan, setDraftLaunchPlan] = createSignal<{ argv: string[] } | null>(null)
  const [showCreate, setShowCreate] = createSignal(false)
  // 组件体只跑一次：聚焦过账（原 useRef）用普通可变变量。
  let focusedInitialAgent: string | null = null

  const panelErrorKey = (operation: string, agentId?: string) => `agent-panel:${operation}:${agentId ?? 'app'}`
  const reportPanelError = (operation: string, error: unknown, agentId?: string) => reportRuntimeError(operation, error, agentId, {
    key: panelErrorKey(operation, agentId),
    scope: agentId ? { kind: 'agent', id: agentId } : { kind: 'app', id: 'agent-settings' },
    source: 'settings.agent-runtime',
  })
  const resolvePanelError = (operation: string, agentId?: string) => resolveRuntimeErrors({ key: panelErrorKey(operation, agentId) })

  const { feedback, setFeedback, toast, notify, configConflict, setConfigConflict, reportConfigMutationError } =
    createAgentPanelFeedback({ reportPanelError })

  const refreshAgents = async () => {
    const list = await agentClient.listAgents()
    useIdentityStore.getState().setAgents(list)
  }

  const { detecting, detectRuntimes, probeFailureByAgentId, ...detection } = createAgentDetection({
    reportPanelError, resolvePanelError, setFeedback,
  })
  // A discovery snapshot can outlive a delete or manual import in this panel.
  // The current registry owns whether a provider is already configured.
  // ⚠️ 候选数组按**报告原引用**直传（Solid For 按对象引用判行——不得在宿主做 map 产生
  // 新对象身份，否则每次 agents 变更整列 DOM 重挂，React 时代 keyed reconcile 的
  // 「原地更新」契约被破坏）；导入态解析改为 lookup prop，由候选行内响应式调用。

  const provisioning = createAgentCandidateProvisioning({
    agentClient, agents, reportPanelError, resolvePanelError, reportConfigMutationError,
    setFeedback, setConfigConflict, notify,
  })

  const reloadConfigSnapshot = async () => {
    try {
      await agentClient.agentConfigSnapshot()
      await refreshAgents()
      setConfigConflict(false)
      setFeedback('配置已重新载入；未提交草稿仍保留。')
      resolvePanelError('重新载入 Agent 配置')
    } catch (error) {
      reportPanelError('重新载入 Agent 配置', error)
      setFeedback('重新载入失败，详情见右下角错误中心')
    }
  }

  // 深链 initialAgentId：目标 Agent 出现于列表时聚焦其编辑卡（一次）。
  createEffect(() => {
    const list = agents()
    const initialAgentId = props.initialAgentId
    if (!initialAgentId || focusedInitialAgent === initialAgentId) return
    const target = list.find(agent => agent.id === initialAgentId)
    if (!target) return
    focusedInitialAgent = initialAgentId
    setEditingId(target.id)
    setDraft(emptyDraft(target))
    setDraftMachine(agentDraftReducer(initialAgentDraftState(), { type: 'select', agentId: target.id }))
    setFeedback('请重新选择或修正该 Agent 的可执行文件。')
  })

  const startEdit = (agent: AgentEntry) => {
    setEditingId(agent.id)
    setDraft(emptyDraft(agent))
    setFeedback(null)
    setDraftLaunchPlan(null)
    setDraftMachine(agentDraftReducer(initialAgentDraftState(), { type: 'select', agentId: agent.id }))
  }

  /** 草稿任一字段变更：指纹更新 + 旧验证立即失效（状态机保证）。 */
  const patchDraft = (updater: (current: Draft) => Draft) => {
    setDraft(current => {
      const next = updater(current)
      setDraftMachine(machine => agentDraftReducer(machine, {
        type: 'edit',
        fingerprint: agentDraftFingerprint({ name: next.name, provider: next.provider, exe: next.exe, args: next.args }),
      }))
      return next
    })
  }

  const saveEdit = async (agentId: string) => {
    if (savingId()) return
    const current = draft()
    const invalid = invocationError(current.exe, current.args)
    if (invalid) { setFeedback(invalid); return }
    // 状态机 fail-closed：只有 verified 且验证过的指纹与草稿当前指纹相等
    // 才能保存（草稿变更/切换 agent/取消都会使旧验证失效）。
    if (draftMachine().agentId !== agentId || !canSaveAgentDraft(draftMachine())) {
      setFeedback('请先测试连接成功，再保存配置变更。')
      return
    }
    setDraftMachine(machine => agentDraftReducer(machine, { type: 'saveBegin' }))
    setSavingId(agentId)
    setFeedback(null)
    try {
      await agentClient.ensureConfigRevision()
      await agentClient.updateAgentFieldPatch(agentId, {
        name: current.name,
        exe: current.exe,
        provider: current.provider.trim() || null,
        ...(current.argsKnown ? { args: [...current.args] } : {}),
      })
      await refreshAgents()
      setDraftMachine(machine => agentDraftReducer(machine, { type: 'saveEnd', ok: true }))
      setEditingId(null)
      setConfigConflict(false)
      setFeedback(null)
      resolvePanelError('保存 Agent 字段', agentId)
      notify(`已保存 ${agentId}`)
    } catch (error) {
      // 保存失败（含 CAS 冲突）：状态机回到 verified，草稿与验证都保留，可重试。
      setDraftMachine(machine => agentDraftReducer(machine, { type: 'saveEnd', ok: false }))
      reportConfigMutationError('保存 Agent 字段', error, agentId)
      notify(`保存失败：${agentId}`)
    } finally {
      setSavingId(null)
    }
  }

  const setDefault = async (agentId: string) => {
    if (savingId()) return
    setSavingId(agentId)
    setFeedback(null)
    try {
      await agentClient.ensureConfigRevision()
      try {
        await agentClient.updateAgentFieldPatch(agentId, { default: true })
      } catch (error) {
        if (wireErrorCode(error) !== 'config_read_only') throw error
        await agentClient.initializeAgentFieldPatch(agentId, { default: true })
      }
      await refreshAgents()
      setConfigConflict(false)
      setFeedback(null)
      resolvePanelError('设置默认 Agent', agentId)
      notify(`已将 ${agentId} 设为默认`)
    } catch (error) {
      reportConfigMutationError('设置默认 Agent', error, agentId)
    } finally {
      setSavingId(null)
    }
  }

  /** issue #67A：删除已连接的 agent runtime 配置条目。
   *  用户裁定口径：仅摘配置 + 停 runtime，**不**删该 agent 的会话与记录数据；
   *  删除前必须让用户看清"将移除什么 / 保留什么"。active agent 先由前端拦一道
   *  （后端 `config_active_agent_protected` 仍是唯一真值）。 */
  const deleteAgent = async (agent: AgentEntry) => {
    if (savingId() || testingId()) return
    if (agent.id === activeAgent()) {
      setFeedback('当前正在使用的 Agent 不能删除，请先切换到其它 Agent。')
      return
    }
    const confirmed = typeof window.confirm === 'function'
      ? window.confirm(
        `确认删除 Agent「${agent.name}」？\n\n将移除：\n  · 配置条目 ${agent.id}（agents.yaml）\n  · 运行中的 runtime 实例（若在运行，将停止）\n\n保留不动：\n  · 该 Agent 的历史会话与记录数据\n  · 其它 Agent 配置`,
      )
      : false
    if (!confirmed) return
    setSavingId(agent.id)
    setFeedback(null)
    try {
      await agentClient.deleteAgent(agent.id)
      if (editingId() === agent.id) {
        setEditingId(null)
        setDraftMachine(initialAgentDraftState())
      }
      await refreshAgents()
      setConfigConflict(false)
      setFeedback(null)
      resolvePanelError('删除 Agent', agent.id)
      notify(`已删除 ${agent.name}（${agent.id}）`)
    } catch (error) {
      reportConfigMutationError('删除 Agent', error, agent.id)
    } finally {
      setSavingId(null)
    }
  }

  const testConnection = async (agentId: string) => {
    if (testingId()) return
    setTestingId(agentId)
    setTestResult(current => ({ ...current, [agentId]: '测试中…' }))
    try {
      const result = await agentClient.testAgentConnection(agentId)
      setTestResult(current => ({
        ...current,
        [agentId]: result.ok
          ? `连接成功（${result.durationMs}ms）`
          : `连接失败：${result.error?.message ?? '未知错误'}`,
      }))
      if (result.ok) {
        resolvePanelError('测试 Agent 连接', agentId)
      } else {
        reportPanelError('测试 Agent 连接', result.error ?? new Error('Agent 连接失败'), agentId)
      }
    } catch (error) {
      const detail = reportPanelError('测试 Agent 连接', error, agentId)
      setTestResult(current => ({ ...current, [agentId]: detail.message }))
    } finally {
      setTestingId(null)
    }
  }

  const testDraftConnection = async (agentId: string) => {
    if (testingId()) return
    const current = draft()
    const invalid = invocationError(current.exe, current.args)
    if (invalid) { setFeedback(invalid); return }
    // 在发起验证前捕获草稿指纹：验证期间用户再改草稿，状态机会作废本次验证。
    const testedFingerprint = agentDraftFingerprint({ name: current.name, provider: current.provider, exe: current.exe, args: current.args })
    setDraftMachine(machine => agentDraftReducer(machine, { type: 'testBegin' }))
    // Solid setter 同步生效：此处读到的已是 testBegin 后的机器（testRequestId 已 +1）。
    const requestId = draftMachine().testRequestId
    setTestingId(agentId)
    try {
      const result = await agentClient.testAgentCandidate(agentId, {
        name: current.name.trim(), provider: current.provider.trim(), transport: 'subprocess', exe: current.exe.trim(), args: [...current.args],
      })
      setDraftLaunchPlan(result.launchPlan && 'argv' in result.launchPlan ? { argv: result.launchPlan.argv } : null)
      if (!result.ok) throw new Error(result.error?.message ?? '连接失败')
      setDraftMachine(machine => agentDraftReducer(machine, {
        type: 'testEnd', requestId, ok: true, testedFingerprint,
        message: `连接成功（${result.durationMs}ms），现在可以保存`,
      }))
      setTestResult(currentState => ({ ...currentState, [agentId]: `连接成功（${result.durationMs}ms），现在可以保存` }))
      setFeedback(null)
    } catch (error) {
      const message = `连接失败：${error instanceof Error ? error.message : String(error)}`
      setDraftMachine(machine => agentDraftReducer(machine, {
        type: 'testEnd', requestId, ok: false, testedFingerprint, message,
      }))
      setTestResult(currentState => ({ ...currentState, [agentId]: message }))
    } finally { setTestingId(null) }
  }

  /** B1：取消进行中的草稿验证——在途结果作废（状态机递增请求序号），可立即重测。
   * testingId 同步复位：Promise 仍会 resolve，但其 finally 与 testEnd 都是无害幂等。 */
  const cancelDraftTest = () => {
    setDraftMachine(machine => agentDraftReducer(machine, { type: 'testCancel' }))
    setTestingId(null)
  }

  const restartRuntime = async (agentId: string) => {
    if (savingId()) return
    setSavingId(agentId)
    setFeedback(null)
    try {
      await agentClient.restartAgentRuntime(agentId)
      await refreshAgents()
      resolvePanelError('重启 Agent runtime', agentId)
      notify(`已重启 ${agentId} 并应用配置`)
    } catch (error) {
      reportConfigMutationError('重启 Agent runtime', error, agentId)
    } finally {
      setSavingId(null)
    }
  }

  const createAgent = async (createDraft: AgentCreateDraftInput) => {
    if (savingId()) return
    const id = createDraft.id.trim()
    // B1：自定义 profile 规则（复用 Codeg 类别）：slug、重复 id、内置 id 冲突、
    // 必填 launch。后端另有同款 slug/重复校验；此处让用户在提交前看到原因。
    const profileIssues = validateCustomProfile(
      { id, name: createDraft.name, exe: createDraft.exe, provider: createDraft.provider },
      agents().map(agent => agent.id),
      builtinAgentCatalog.providers(),
    )
    if (profileIssues.length > 0) {
      setFeedback(profileIssues.map(issue => issue.message).join('；'))
      return
    }
    const invalid = invocationError(createDraft.exe, createDraft.args)
    if (invalid) { setFeedback(invalid); return }
    setSavingId(id)
    setFeedback(null)
    const config = agentConfig(createDraft.name, createDraft.exe, createDraft.args, createDraft.provider, agents().length === 0)
    // SAFETY: AgentCreateConfig 是扁平 JSON 对象的命名类型；此断言只把它扩宽为按**键名**读取的
    // 视图（assertCustomProfileFieldsAllowed 仅遍历 Object.keys，不读值），结构不变、不丢字段。
    assertCustomProfileFieldsAllowed(config as unknown as Record<string, unknown>)
    try {
      await agentClient.ensureConfigRevision()
      await agentClient.createAgent(id, config)
      await refreshAgents()
      setShowCreate(false)
      setConfigConflict(false)
      setFeedback(null)
      resolvePanelError('新建 Agent', id)
      notify(`已新建 Agent ${id}`)
    } catch (error) {
      // 施工文档 §4.6：embedded source 首次配置——create 撞 config_read_only 时，
      // 自动改为在 exe 旁初始化外部 agents.yaml（同一最小配置）。
      if (wireErrorCode(error) === 'config_read_only') {
        try {
          await agentClient.initializeAgentsConfig(id, agentsDocument(id, config))
          await refreshAgents()
          resolvePanelError('初始化 Agent 配置', id)
          setShowCreate(false)
          setFeedback(`已初始化外部配置并新建 Agent ${id}`)
        } catch (initError) {
          reportConfigMutationError('初始化 Agent 配置', initError, id)
        }
        return
      }
      reportConfigMutationError('新建 Agent', error, id)
    } finally {
      setSavingId(null)
    }
  }

  return (
    <div class="agent-runtime-panel">
      <Show when={toast()}>
        <div class="agent-runtime-toast" role="status" aria-live="polite">{toast()}</div>
      </Show>
      <Show when={feedback()}><div class="set-hint" role="status">{feedback()}</div></Show>
      <Show when={configConflict()}>
        <button type="button" class="set-btn" onClick={() => void reloadConfigSnapshot()}>
          重新载入配置
        </button>
      </Show>

      <Show when={agents().length === 0}>
        <div class="set-hint" role="status">
          当前没有 Agent 配置。点击“新建 Agent”创建首个外部配置。
        </div>
      </Show>

      <For each={agents()}>{agent => {
        const status = () => selectAgentStatus(agent.id, activeAgent(), agentStatuses())
        return (
          <AgentRuntimeCard
            agent={agent}
            activeAgent={activeAgent()}
            status={status()}
            isEditing={editingId() === agent.id}
            draft={draft()}
            onPatchDraft={patchDraft}
            draftLaunchPlan={draftLaunchPlan()}
            draftMachinePhase={draftMachine().phase}
            probeFailure={probeFailureByAgentId().get(agent.id)}
            detecting={detecting()}
            onRedetect={() => { void detectRuntimes(true) }}
            savingId={savingId()}
            testingId={testingId()}
            testResultText={testResult()[agent.id]}
            onStartEdit={() => startEdit(agent)}
            onSaveEdit={() => { void saveEdit(agent.id) }}
            onTestDraftConnection={() => { void testDraftConnection(agent.id) }}
            onCancelDraftTest={cancelDraftTest}
            onCancelEdit={() => { setEditingId(null); setDraftMachine(initialAgentDraftState()) }}
            onSetDefault={() => { void setDefault(agent.id) }}
            onTestConnection={() => { void testConnection(agent.id) }}
            onRestartRuntime={() => { void restartRuntime(agent.id) }}
            onDeleteAgent={() => { void deleteAgent(agent) }}
          />
        )
      }}</For>

      <AgentCandidateList
        candidates={detection.candidates()}
        resolveImportedAgentId={candidate => {
          const currentAgents = agents()
          return currentAgents.find(agent => agent.id === candidate.alreadyImportedAgentId || agent.provider === candidate.provider)?.id
        }}
        selectedCandidateId={detection.selectedCandidateId()}
        onSelectCandidate={detection.setSelectedCandidateId}
        detectionDiagnostics={detection.detectionDiagnostics()}
        detectionElapsedMs={detection.detectionElapsedMs()}
        detectionPreflight={detection.detectionPreflight()}
        detectionTruncated={detection.detectionTruncated()}
        detectionCompleted={detection.detectionCompleted()}
        detecting={detecting()}
        onRedetect={() => { void detectRuntimes(true) }}
        onCancelDetection={detection.cancelDetection}
        onManualCreate={() => setShowCreate(true)}
        candidateDrafts={provisioning.candidateDrafts()}
        candidateValidation={provisioning.candidateValidation()}
        importedCandidateIds={provisioning.importedCandidateIds()}
        candidateErrors={provisioning.candidateErrors()}
        provisioningCandidateId={provisioning.provisioningCandidateId()}
        provisioningPhase={provisioning.provisioningPhase()}
        onCancelValidation={provisioning.cancelCandidateValidation}
        onValidateAndImport={candidate => { void provisioning.validateAndImportCandidate(candidate) }}
        onImportUnverified={candidate => { void provisioning.importUnverifiedCandidate(candidate) }}
        onActivateImported={candidate => { void provisioning.activateImportedCandidate(candidate) }}
        onUpdateCandidateDraft={provisioning.updateCandidateDraft}
      />

      <div class="set-preset-row" style={{ 'margin-top': '12px' }}>
        <button class="ps-btn sm" type="button" onClick={() => setShowCreate(value => !value)}>
          {showCreate() ? '收起新建' : '新建 Agent'}
        </button>
      </div>

      <Show when={showCreate()}>
        <AgentCreateForm busy={savingId() !== null} onCreate={createAgent} />
      </Show>
    </div>
  )
}
