// src/components/settings/InvocationPreview.solid.tsx
/** @jsxImportSource solid-js */
import { createMemo, For } from 'solid-js'
import { describeInvocation } from '../../domains/agent/invocationDraft.ts'

export interface InvocationPreviewProps {
  executable: string
  args: string[]
  effectiveArgs?: string[]
}

/**
 * 草稿启动命令预览（实际启动串 + 校验 issue 行；编辑/候选/新建三处共用）。
 * #515 W1：Solid 实体（原 React 面同批退役；DOM/role 契约逐字保持）。
 */
export default function InvocationPreview(props: InvocationPreviewProps) {
  const invocation = createMemo(() => describeInvocation(
    { executable: props.executable, args: props.args },
    props.effectiveArgs ?? props.args,
  ))
  return (
    <div class="agent-invocation-preview">
      <div class="set-hint">实际启动：<code>{invocation().display}</code></div>
      <For each={invocation().validation.issues}>{issue => (
        <div class="set-hint" role={issue.severity === 'error' ? 'alert' : 'note'}>
          {issue.severity === 'error' ? '错误' : '提示'}：{issue.message}
        </div>
      )}</For>
    </div>
  )
}

// src/components/settings/InvocationPreview.tsx
import { describeInvocation } from '../../domains/agent/invocationDraft.ts'

/** 草稿启动命令预览（实际启动串 + 校验 issue 行；编辑/候选/新建三处共用）。 */
export default function InvocationPreview({ executable, args, effectiveArgs = args }: {
  executable: string
  args: string[]
  effectiveArgs?: string[]
}) {
  const invocation = describeInvocation({ executable, args }, effectiveArgs)
  return (
    <div className="agent-invocation-preview">
      <div className="set-hint">实际启动：<code>{invocation.display}</code></div>
      {invocation.validation.issues.map(issue => (
        <div className="set-hint" role={issue.severity === 'error' ? 'alert' : 'note'} key={`${issue.code}:${issue.argumentIndex ?? 'exe'}`}>
          {issue.severity === 'error' ? '错误' : '提示'}：{issue.message}
        </div>
      ))}
    </div>
  )
}
