// src/components/chat/GenerationFooter.tsx
import { useEffect, useMemo, useState, type CSSProperties } from 'react'
import { Square } from 'lucide-react'
import { resolveSpinnerMarker } from './spinnerFrames'
import { resolveActivity, resolveFrame, resolveStallProgress } from './spinnerMachine'
import { getSpinnerAssetPreset, getSpinnerVerbPreset } from './spinnerAssets'
import { normalizeSpinnerVerbs } from './spinnerVerbs'
import SpinnerGlimmer from './SpinnerGlimmer'
import { useStore } from '../../store'
import { useMinDisplayTime } from './useMinDisplayTime'
import { resolveActivityLine } from '../../domains/activity/activityLine.ts'
import { activeTask } from '../../domains/tasks/taskSelectors.ts'
import { useChatRuntimeSnapshot } from './useChatRuntimeSnapshot'
import { nextTokenCatchUp } from './tokenCatchUp.ts'
import type { SpinnerMotionKind } from './spinnerMotion'
import { useShallow } from 'zustand/react/shallow'

const IDIOMS = getSpinnerVerbPreset('zh').verbs
const GLIMMER_CYCLE_MS = 3200

export interface GenerationSummary {
  elapsedMs: number
  tokenCount: number
  completedFrame: string
  reason: 'done' | 'cancelled' | 'error'
}

function formatElapsed(elapsedMs: number) {
  const elapsed = Math.floor(elapsedMs / 1000)
  return elapsed >= 60 ? `${Math.floor(elapsed / 60)}m ${elapsed % 60}s` : `${elapsed}s`
}

function formatTokens(n: number) {
  if (n >= 1000) { const k = n / 1000; return k >= 10 ? `${Math.round(k)}k` : `${k.toFixed(1)}k` }
  return `${n}`
}

export type GenerationPhase =
  | { kind: 'thinking' }
  | { kind: 'tool'; name: string }
  | { kind: 'responding' }

// ── P1-08 热路径叶子：高频 tick 隔离到叶子，父级不随 40-120ms tick 重渲染 ──

/** 帧动画（elapsed 由本组件持 tick 推进） */
function SpinnerFrame({ frames, baseElapsedMs, intervalMs, motion, direction, color, fontSize, running, reduceMotion }: {
  frames: string[]
  baseElapsedMs: number
  intervalMs: number
  motion: SpinnerMotionKind
  direction?: 'forward' | 'reverse' | 'alternate'
  color?: string
  fontSize: number
  running: boolean
  reduceMotion: boolean
}) {
  const [tick, setTick] = useState(0)
  useEffect(() => {
    if (!running) return
    const id = setInterval(() => setTick(value => value + 1), Math.max(40, Math.min(1000, intervalMs || 120)))
    return () => clearInterval(id)
  }, [running, intervalMs])
  const frame = resolveFrame(frames, baseElapsedMs + tick * (intervalMs || 120), intervalMs, reduceMotion ? 'static' : motion, direction)
  return <span className="spinner-frame" style={{ color: color || undefined, fontSize: `${fontSize}px` }}>{frame.char}</span>
}

/** token 追赶计数：显示值向真实值递增，永不超过真实值（P1-08） */
function TokenCounter({ real, running }: { real: number; running: boolean }) {
  const [displayed, setDisplayed] = useState(0)
  useEffect(() => {
    if (!running) return
    const id = setInterval(() => setDisplayed(previous => nextTokenCatchUp(previous, real)), 120)
    return () => clearInterval(id)
  }, [running, real])
  const current = Math.min(displayed, real)
  return <span>↓ {formatTokens(current)} tokens</span>
}

/** 思考已持续时长（D30，1s tick 实时增长） */
function ThinkingDuration({ startedAt, running }: { startedAt: number; running: boolean }) {
  const [, forceTick] = useState(0)
  useEffect(() => {
    if (!running) return
    const id = setInterval(() => forceTick(value => value + 1), 1000)
    return () => clearInterval(id)
  }, [running])
  return <span>思考 {formatElapsed(Math.max(0, Date.now() - startedAt))}</span>
}

/** 生成总耗时（1s tick） */
function ElapsedTimer({ startTime, running }: { startTime: number; running: boolean }) {
  const [, forceTick] = useState(0)
  useEffect(() => {
    if (!running) return
    const id = setInterval(() => forceTick(value => value + 1), 1000)
    return () => clearInterval(id)
  }, [running])
  return <span>{formatElapsed(Math.max(0, Date.now() - startTime))}</span>
}

/** stalled 渐变红强度（P1-08）：把 --stall-progress 传给 .term-spinner 内的子树 */
function StallProbe({ idleMsBase, running, children }: { idleMsBase: number; running: boolean; children: React.ReactNode }) {
  const [tick, setTick] = useState(0)
  useEffect(() => {
    if (!running) return
    const id = setInterval(() => setTick(value => value + 1), 120)
    return () => clearInterval(id)
  }, [running])
  const progress = resolveStallProgress(idleMsBase + tick * 120)
  return (
    <span className="spinner-stall-probe" aria-hidden="true" style={{ '--stall-progress': progress.toFixed(3) } as CSSProperties}>
      {children}
    </span>
  )
}

export default function GenerationFooter({ running, frames, tokenCount, startTime, lastTokenAt, summary, phase, source, onStop }: {
  running: boolean
  frames: string[]
  tokenCount: number
  startTime: number
  lastTokenAt?: number
  summary: GenerationSummary | null
  phase?: GenerationPhase
  source: string | null
  onStop?: () => void
}) {
  const {
    spinnerColor,
    spinnerSize,
    spinnerVerbSet,
    spinnerCustomVerbs,
    spinnerDoneMarker,
    spinnerCancelledMarker,
    spinnerErrorMarker,
    spinnerDoneMarkerMode,
    spinnerCancelledMarkerMode,
    spinnerErrorMarkerMode,
    spinnerIntervalMs,
    spinnerFramePreset,
  } = useStore(useShallow(s => ({
    spinnerColor: s.spinnerColor,
    spinnerSize: s.spinnerSize,
    spinnerVerbSet: s.spinnerVerbSet,
    spinnerCustomVerbs: s.spinnerCustomVerbs,
    spinnerDoneMarker: s.spinnerDoneMarker,
    spinnerCancelledMarker: s.spinnerCancelledMarker,
    spinnerErrorMarker: s.spinnerErrorMarker,
    spinnerDoneMarkerMode: s.spinnerDoneMarkerMode,
    spinnerCancelledMarkerMode: s.spinnerCancelledMarkerMode,
    spinnerErrorMarkerMode: s.spinnerErrorMarkerMode,
    spinnerIntervalMs: s.spinnerIntervalMs,
    spinnerFramePreset: s.spinnerFramePreset,
  })))
  const reduceMotion = window.matchMedia?.('(prefers-reduced-motion: reduce)').matches === true
  const verbPreset = getSpinnerVerbPreset(spinnerVerbSet)
  const verbs = spinnerVerbSet === 'custom'
    ? normalizeSpinnerVerbs(spinnerCustomVerbs, IDIOMS)
    : verbPreset.verbs
  const safeVerbs = verbs.length > 0 ? verbs : IDIOMS
  // safeVerbs 由 spinnerVerbSet/spinnerCustomVerbs 推导，已在 deps 覆盖（传递依赖）
  // eslint-disable-next-line react-hooks/exhaustive-deps
  const randomVerb = useMemo(() => safeVerbs[Math.floor(Math.random() * safeVerbs.length)] || IDIOMS[0], [startTime, spinnerVerbSet, spinnerCustomVerbs])
  const frameAsset = getSpinnerAssetPreset(spinnerFramePreset)
  // P1-08：横向订阅读当前 source 的 plan 与 thinkingStart（plan activeTask 覆盖链最高优先）
  const { tasks, thinkingStart } = useChatRuntimeSnapshot(source)
  const marker = summary
    ? resolveSpinnerMarker(
      frames,
      summary.reason === 'cancelled'
        ? spinnerCancelledMarkerMode
        : summary.reason === 'error'
          ? spinnerErrorMarkerMode
          : spinnerDoneMarkerMode,
      summary.reason === 'cancelled'
        ? spinnerCancelledMarker
        : summary.reason === 'error'
          ? spinnerErrorMarker
          : spinnerDoneMarker,
    )
    : ''
  const now = Date.now()
  const idleMs = running && lastTokenAt ? Math.max(0, now - lastTokenAt) : running ? now - startTime : 0
  // D5/D6：activityLine 覆盖链（plan → tool → thinking/responding → 随机）
  const activeTaskContent = activeTask(tasks)?.content
  const line = resolveActivityLine({
    activeTaskContent,
    toolTitle: phase?.kind === 'tool' ? phase.name : undefined,
    phase: phase?.kind === 'tool' ? 'tool' : phase?.kind === 'thinking' ? 'thinking' : phase?.kind === 'responding' ? 'responding' : undefined,
    thinkingStart,
    now,
    fallbackVerb: randomVerb,
  })
  // ACP 远端调用容忍窗口：3s waiting、10s stalled；tool 阶段抑制 stall。
  const activity = line.stallSuppressed ? 'active' : resolveActivity(idleMs)
  // CC 风格（cc 动词集）：显示幽默随机动词而非阶段文案（plan activeTask 覆盖仍最高优先）
  const ccVerbs = spinnerVerbSet === 'cc'
  const verb = !running ? '' : activity === 'active'
    ? (ccVerbs && !activeTaskContent ? randomVerb : line.activity)
    : activity === 'waiting' ? '等待响应' : '仍在等待后端响应'
  const displayVerb = useMinDisplayTime(verb, 1200)

  if (running) {
    return (
      <div className="term-spinner-row">
        {/* cc 帧：不设 data-phase（帧恒 spinnerColor，颜色不随阶段跳，对齐 CC 恒色） */}
        <div className="term-spinner" data-activity={activity} data-phase={spinnerFramePreset === 'cc' ? undefined : phase?.kind || 'idle'}>
          <StallProbe idleMsBase={idleMs} running={running}>
            <SpinnerFrame frames={frames} baseElapsedMs={now - startTime} intervalMs={spinnerIntervalMs || 120}
              motion={frameAsset.motion} direction={frameAsset.direction} color={spinnerColor}
              fontSize={spinnerSize} running={running} reduceMotion={reduceMotion} />
            <SpinnerGlimmer text={displayVerb} running={running} activity={activity} reducedMotion={reduceMotion} color={spinnerColor} cycleMs={GLIMMER_CYCLE_MS} />
          </StallProbe>
          <span className="spinner-meta">(
            <ElapsedTimer startTime={startTime} running={running} />
            {phase?.kind === 'thinking' && thinkingStart != null && <><span> · </span><ThinkingDuration startedAt={thinkingStart} running={running} /></>}
            {tokenCount > 0 && <><span> · </span><TokenCounter real={tokenCount} running={running} /></>}
          )</span>
          {activity !== 'active' && <span className="spinner-activity" aria-live="polite">…</span>}
        </div>
        {onStop && <button className="spinner-stop-btn" title="停止生成 (Esc / Ctrl+C)" onClick={onStop}>
          <Square size={11} /> 停止
        </button>}
      </div>
    )
  }

  if (!summary) return null
  return (
    <div className={`term-summary term-summary-${summary.reason}`}>
      <span className="term-summary-frame" style={{ fontSize: `${spinnerSize}px` }}>
        {marker}
      </span>
      <span>{summary.reason === 'cancelled' ? '已停止' : summary.reason === 'error' ? '处理失败' : '生成完毕（处理耗时）'} {formatElapsed(summary.elapsedMs)}</span>
    </div>
  )
}

// src/renderers/solid-workbench/chat/GenerationFooter.solid.tsx
import { For, Show, createEffect, createMemo, createSignal, onCleanup, onMount } from 'solid-js'
import { resolveActivityLine } from '../../../domains/activity/activityLine.ts'
import { resolveSpinnerMarker } from '../../../components/chat/spinnerFrames.ts'
import { glimmerIntensity, resolveActivity, resolveFrame, resolveGlimmer, resolveStallProgress } from '../../../components/chat/spinnerMachine.ts'
import { nextTokenCatchUp } from '../../../components/chat/tokenCatchUp.ts'
import { segmentGraphemes } from '../../../utils/textWidth.ts'
import {
  browserWorkbenchClock,
  type GenerationFooterInput,
  type GenerationFooterLifecycle,
  type WorkbenchClock,
} from '../../../domains/workbench/generationFooterContracts.ts'

const GLIMMER_CYCLE_MS = 4600
const HOT_TICK_MS = 120
const SLOW_TICK_MS = 1000
const MIN_VERB_DISPLAY_MS = 1200

export interface SolidGenerationFooterProps extends GenerationFooterInput {
  /** ChatView usage is intentionally hidden until the product surface is redesigned. */
  showTokenCount?: boolean
  clock?: WorkbenchClock
  random?: () => number
  onLifecycleReady?: (lifecycle: GenerationFooterLifecycle) => void
}

export function SolidGenerationFooter(props: SolidGenerationFooterProps) {
  const clock = () => props.clock ?? browserWorkbenchClock
  const [now, setNow] = createSignal(clock().now())
  const [displayedTokens, setDisplayedTokens] = createSignal(0)
  const [displayedVerb, setDisplayedVerb] = createSignal('')
  const [paused, setPaused] = createSignal(false)
  let hotTimer: unknown | null = null
  let slowTimer: unknown | null = null
  let verbTimer: unknown | null = null
  let destroyed = false
  let lastVerbShownAt = 0
  let observedStartTime = props.startTime
  let effectiveStartTime = normalizeGenerationStart(props.startTime, clock().now())

  const clearHotTimer = () => {
    if (hotTimer !== null) clock().clearInterval(hotTimer)
    hotTimer = null
  }
  const clearSlowTimer = () => {
    if (slowTimer !== null) clock().clearInterval(slowTimer)
    slowTimer = null
  }
  const clearVerbTimer = () => {
    if (verbTimer !== null) clock().clearTimeout(verbTimer)
    verbTimer = null
  }
  const syncTimers = () => {
    clearHotTimer()
    clearSlowTimer()
    if (destroyed || paused() || !props.running) return
    hotTimer = clock().setInterval(() => {
      setNow(clock().now())
      setDisplayedTokens(previous => nextTokenCatchUp(previous, props.tokenCount))
    }, Math.max(40, Math.min(1000, props.appearance.intervalMs || HOT_TICK_MS)))
    slowTimer = clock().setInterval(() => setNow(clock().now()), SLOW_TICK_MS)
  }

  const lifecycle: GenerationFooterLifecycle = {
    pause() {
      if (destroyed || paused()) return
      setPaused(true)
      clearHotTimer()
      clearSlowTimer()
      clearVerbTimer()
    },
    resume() {
      if (destroyed || !paused()) return
      setPaused(false)
      setNow(clock().now())
      syncTimers()
    },
    destroy() {
      if (destroyed) return
      destroyed = true
      clearHotTimer()
      clearSlowTimer()
      clearVerbTimer()
    },
  }

  onMount(() => {
    setNow(clock().now())
    syncTimers()
    props.onLifecycleReady?.(lifecycle)
  })
  onCleanup(() => lifecycle.destroy())

  createEffect(() => {
    const timerInputs = [props.running, props.appearance.intervalMs, paused()] as const
    if (timerInputs.length > 0) syncTimers()
  })

  createEffect(() => {
    const nextStartTime = props.startTime
    if (nextStartTime === observedStartTime) return
    observedStartTime = nextStartTime
    effectiveStartTime = normalizeGenerationStart(nextStartTime, clock().now())
  })

  createEffect(() => {
    const real = Math.max(0, props.tokenCount)
    if (!props.running) setDisplayedTokens(real)
    else if (displayedTokens() > real) setDisplayedTokens(real)
  })

  const fallbackVerb = createMemo(() => {
    const verbs = props.appearance.verbs.length > 0 ? props.appearance.verbs : ['思考中']
    const randomValue = Math.max(0, Math.min(0.999999, (props.random ?? Math.random)()))
    return verbs[Math.floor(randomValue * verbs.length)] ?? verbs[0]!
  })
  const idleMs = () => props.running
    ? Math.max(0, now() - (props.lastTokenAt ?? props.startTime))
    : 0
  const line = createMemo(() => resolveActivityLine({
    activeTaskContent: props.activeTaskContent,
    toolTitle: props.phase?.kind === 'tool' ? props.phase.name : undefined,
    phase: props.phase?.kind,
    thinkingStart: props.thinkingStart,
    now: now(),
    fallbackVerb: fallbackVerb(),
  }))
  const activity = () => line().stallSuppressed ? 'active' : resolveActivity(idleMs())
  const desiredVerb = () => {
    if (!props.running) return ''
    if (activity() === 'waiting') return '等待响应'
    if (activity() === 'stalled') return '仍在等待后端响应'
    return props.appearance.verbSet === 'cc' && !props.activeTaskContent
      ? fallbackVerb()
      : line().activity
  }

  createEffect(() => {
    const next = desiredVerb()
    clearVerbTimer()
    const elapsed = clock().now() - lastVerbShownAt
    if (!displayedVerb() || elapsed >= MIN_VERB_DISPLAY_MS) {
      lastVerbShownAt = clock().now()
      setDisplayedVerb(next)
      return
    }
    verbTimer = clock().setTimeout(() => {
      lastVerbShownAt = clock().now()
      setDisplayedVerb(next)
      verbTimer = null
    }, MIN_VERB_DISPLAY_MS - elapsed)
  })

  const elapsedMs = () => Math.max(0, now() - effectiveStartTime)
  const frame = () => resolveFrame(
    [...props.appearance.frames],
    elapsedMs(),
    props.appearance.intervalMs,
    props.reducedMotion ? 'static' : props.appearance.motion,
    props.appearance.direction,
  ).char
  const stallProgress = () => resolveStallProgress(idleMs())
  const shownTokens = () => Math.min(displayedTokens(), Math.max(0, props.tokenCount))
  const summaryMarker = () => props.summary
    ? resolveSpinnerMarker(
      [...props.appearance.frames],
      props.summary.reason === 'cancelled'
        ? props.appearance.cancelledMarkerMode
        : props.summary.reason === 'error'
          ? props.appearance.errorMarkerMode
          : props.appearance.doneMarkerMode,
      props.summary.reason === 'cancelled'
        ? props.appearance.cancelledMarker
        : props.summary.reason === 'error'
          ? props.appearance.errorMarker
          : props.appearance.doneMarker,
    )
    : ''

  return (
    <Show when={props.running} fallback={<GenerationSummaryView input={props} marker={summaryMarker()} />}>
      <div class="term-spinner-row">
        <div
          class="term-spinner"
          data-activity={activity()}
          data-phase={props.appearance.framePreset === 'cc' ? undefined : props.phase?.kind || 'idle'}
          style={{ '--stall-progress': stallProgress().toFixed(3) }}
        >
          <span class="spinner-frame" style={{ color: props.appearance.color || undefined, 'font-size': `${props.appearance.size}px` }}>
            {frame()}
          </span>
          <SolidSpinnerGlimmer
            text={displayedVerb()}
            elapsedMs={elapsedMs()}
            active={activity() === 'active'}
            reducedMotion={props.reducedMotion === true}
            color={props.appearance.color}
          />
          <span class="spinner-meta">(
            <span>{formatElapsed(elapsedMs())}</span>
            <Show when={props.phase?.kind === 'thinking' && props.thinkingStart != null}>
              <span> · </span><span>思考 {formatElapsed(Math.max(0, now() - (props.thinkingStart ?? now())))}</span>
            </Show>
            <Show when={props.showTokenCount === true && props.tokenCount > 0}>
              <span> · </span><span>↓ {formatTokens(shownTokens())} tokens</span>
            </Show>
          )</span>
          <Show when={activity() !== 'active'}><span class="spinner-activity" aria-live="polite">…</span></Show>
        </div>
        <Show when={props.onStop}>
          {onStop => <button class="spinner-stop-btn" type="button" title="停止生成 (Esc / Ctrl+C)" onClick={onStop()}>
            <span aria-hidden="true">■</span> 停止
          </button>}
        </Show>
      </div>
    </Show>
  )
}

function SolidSpinnerGlimmer(props: {
  text: string
  elapsedMs: number
  active: boolean
  reducedMotion: boolean
  color?: string
}) {
  const graphemes = () => segmentGraphemes(props.text)
  const activeIndex = () => props.reducedMotion || !props.active || graphemes().length === 0
    ? -1
    : resolveGlimmer(props.text, props.elapsedMs, GLIMMER_CYCLE_MS).glimmerIndex
  return (
    <span
      class="spinner-verb"
      data-glimmer-active={activeIndex() >= 0 ? 'true' : 'false'}
      style={{ '--spinner-glimmer-color': props.color || undefined }}
    >
      <For each={graphemes()}>{(grapheme, index) => {
        const intensity = () => glimmerIntensity(index(), activeIndex())
        const className = () => intensity() === 2
          ? 'spinner-glimmer spinner-glimmer-core'
          : intensity() === 1
            ? 'spinner-glimmer spinner-glimmer-edge'
            : undefined
        return <span class={className()}>{grapheme}</span>
      }}</For>
    </span>
  )
}

function GenerationSummaryView(props: { input: GenerationFooterInput; marker: string }) {
  return (
    <Show when={props.input.summary}>
      {summary => (
        <div class={`term-summary term-summary-${summary().reason}`}>
          <span class="term-summary-frame" style={{ 'font-size': `${props.input.appearance.size}px` }}>{props.marker}</span>
          <span>
            {summary().reason === 'cancelled' ? '已停止' : summary().reason === 'error' ? '处理失败' : '处理耗时'} {formatElapsed(summary().elapsedMs)}
          </span>
        </div>
      )}
    </Show>
  )
}

export function formatElapsed(elapsedMs: number): string {
  const elapsed = Math.floor(Math.max(0, elapsedMs) / 1000)
  return elapsed >= 60 ? `${Math.floor(elapsed / 60)}m ${elapsed % 60}s` : `${elapsed}s`
}

export function formatTokens(value: number): string {
  const n = Math.max(0, value)
  if (n >= 1000) {
    const thousands = n / 1000
    return thousands >= 10 ? `${Math.round(thousands)}k` : `${thousands.toFixed(1)}k`
  }
  return `${Math.floor(n)}`
}

function normalizeGenerationStart(startTime: number, now: number): number {
  if (Number.isFinite(startTime) && startTime >= 0) {
    // Epoch zero is valid for deterministic tests, but never for a real 2020+
    // browser clock. Treat missing/legacy zero as "started now".
    if (startTime > 0 || now < 86_400_000) return Math.min(startTime, now)
  }
  return now
}
